// Code generated by "go run err_generate.go"; DO NOT EDIT.

package sign

import (
	"fmt"
	"log/slog"
)

func (h *Sign) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Sign) Key() string { return "sign" }

var log = slog.Default().With("handler", "sign")
