// Code generated by "go run err_generate.go"; DO NOT EDIT.

package sign

import (
	"fmt"
	"log/slog"
)

func (s *Sign) Err(err error) error { return fmt.Errorf("%s: %s", s.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (s *Sign) Key() string { return "sign" }

var log = func() *slog.Logger { return slog.Default().With("handler", "sign") }
