// Code generated by "go run err_generate.go"; DO NOT EDIT.

package id

import (
	"fmt"
	"log/slog"
)

func (i *Id) Err(err error) error { return fmt.Errorf("%s: %s", i.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (i *Id) Key() string { return "id" }

var log = func() *slog.Logger { return slog.Default().With("handler", "id") }
