//go:build ignore

// err_generate generates zerr.go which houses the handler.Err method.

package main

import (
	"bytes"
	"html/template"
	"log"
	"path/filepath"
	"strings"

	"codeberg.org/miekg/dns/cmd/testserv/internal/generate"
)

const hdr = `
// Code generated by "go run err_generate.go"; DO NOT EDIT.

import "fmt"

`

var funcmap = template.FuncMap{
	"tolower": strings.ToLower,
}

func main() {
	handlers, err := generate.Handlers()
	if err != nil {
		log.Fatal(err)
	}
	source := &bytes.Buffer{}
	source.WriteString(hdr)

	for _, handler := range handlers {
		out := filepath.Join(strings.ToLower(handler), "zerr.go")
		ErrFunc := template.Must(template.New("errFunc").Funcs(funcmap).Parse(`
func (h *{{.}}) Err(err error) error { return fmt.Errorf("handler/{{tolower .}}: %s", err.Error()) }
`))

		if err := ErrFunc.Execute(source, handler); err != nil {
			log.Fatalf("Failed to generate %s: %v", out, err)
		}
		generate.Write(source, out)
	}
}
