//go:build ignore

// string_generate generates zstring.go which houses the StringToHandler map.

package main

import (
	"bytes"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"strings"

	"codeberg.org/miekg/dns/cmd/testserv/internal/generate"
)

const hdr = `
// Code generated by "go run string_generate.go"; DO NOT EDIT.

package handlers

`

var funcmap = template.FuncMap{
	"tolower": strings.ToLower,
}

var StringToHandler = template.Must(template.New("stringToHandler").Funcs(funcmap).Parse(`
{{range .}} import "codeberg.org/miekg/dns/cmd/testserv/handlers/{{tolower .}}"
{{end}}

// StringToHandler is a map of strings to a handler creation function..
var StringToHandler = map[string]func() Handler {
{{range .}} "{{tolower .}}": func() Handler { return new({{tolower .}}.{{.}}) },
{{end}}
}

`))

const out = "zstring.go"

func main() {
	subdirs, err := os.ReadDir(".")
	if err != nil {
		log.Fatal(err)
	}
	handlers := []string{}
	source := &bytes.Buffer{}
	source.WriteString(hdr)
	for _, d := range subdirs {
		if !d.IsDir() {
			continue
		}
		handler := filepath.Join(d.Name(), d.Name()+".go")
		types, err := generate.Types(handler)
		if err != nil {
			log.Fatal(err)
		}
		handlers = append(handlers, types...)
	}

	if err := StringToHandler.Execute(source, handlers); err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}

	generate.Write(source, out)
}
