// Code generated by "go run string_generate.go"; DO NOT EDIT.

package handlers

import "codeberg.org/miekg/dns/cmd/testserv/handlers/any"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/as112"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/chaos"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/cookie"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/dbfile"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/log"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/metrics"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/nsid"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/refuse"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/sign"
import "codeberg.org/miekg/dns/cmd/testserv/handlers/unpack"

// StringToHandler is a map of strings to a handler creation function.
var StringToHandler = map[string]func() Handler{
	"any":     func() Handler { return new(any.Any) },
	"as112":   func() Handler { return new(as112.As112) },
	"chaos":   func() Handler { return new(chaos.Chaos) },
	"cookie":  func() Handler { return new(cookie.Cookie) },
	"dbfile":  func() Handler { return new(dbfile.Dbfile) },
	"log":     func() Handler { return new(log.Log) },
	"metrics": func() Handler { return new(metrics.Metrics) },
	"nsid":    func() Handler { return new(nsid.Nsid) },
	"refuse":  func() Handler { return new(refuse.Refuse) },
	"sign":    func() Handler { return new(sign.Sign) },
	"unpack":  func() Handler { return new(unpack.Unpack) },
}
