// Code generated by "go run err_generate.go"; DO NOT EDIT.

package ecs

import (
	"fmt"
	"log/slog"

	"codeberg.org/miekg/dns/cmd/atomdns/internal/dnslog"
)

func (e *Ecs) Err(err error) error { return fmt.Errorf("%s: %w", e.Key(), err) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (e *Ecs) Key() string { return "ecs" }

var log = func() *slog.Logger { return slog.Default().With("handler", "ecs") }
