// Code generated by "go run err_generate.go"; DO NOT EDIT.

package ecs

import (
	"fmt"
	"log/slog"
)

func (e *Ecs) Err(err error) error { return fmt.Errorf("%s: %s", e.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (e *Ecs) Key() string { return "ecs" }

var log = func() *slog.Logger { return slog.Default().With("handler", "ecs") }
