// Code generated by "go run err_generate.go"; DO NOT EDIT.

package yes

import (
	"fmt"
	"log/slog"
)

func (h *Yes) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Yes) Key() string { return "yes" }

var log = func() *slog.Logger { return slog.Default().With("handler", "yes") }
