// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbfile

import (
	"fmt"
	"log/slog"
)

func (d *Dbfile) Err(err error) error { return fmt.Errorf("%s: %s", d.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (d *Dbfile) Key() string { return "dbfile" }

var log = func() *slog.Logger { return slog.Default().With("handler", "dbfile") }
