// Code generated by "go run string_generate.go"; DO NOT EDIT.

package dnsserver

// Handlers is a slices of hanlder names.
var Handlers = []string{
	"acl",
	"any",
	"as112",
	"chaos",
	"cookie",
	"dbfile",
	"dbhost",
	"dbsqlite",
	"drunk",
	"log",
	"metrics",
	"nsid",
	"refuse",
	"sign",
	"template",
	"unpack",
	"whoami",
}
