// Code generated by "go run err_generate.go"; DO NOT EDIT.

package global

import "fmt"
import "log/slog"

func (h *Global) Err(err error) error { return fmt.Errorf("handler.global: %s", err.Error()) }

var log = slog.Default().With("handler", "global")
