// Code generated by "go run err_generate.go"; DO NOT EDIT.

package log

import (
	"fmt"
	"log/slog"
)

func (l *Log) Err(err error) error { return fmt.Errorf("%s: %w", l.Key(), err) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (l *Log) Key() string { return "log" }

var _log = func() *slog.Logger { return slog.Default().With("handler", "log") }
