// Code generated by "go run err_generate.go"; DO NOT EDIT.

package log

import "fmt"
import "log/slog"

func (h *Log) Err(err error) error { return fmt.Errorf("handler.log: %s", err.Error()) }

var _log = slog.Default().With("handler", "log")
