//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"log"
	"strings"

	"codeberg.org/miekg/dns/internal/generate"
)

var hdr = `
// Code generated by "go run compare_generate.go"; DO NOT EDIT.

package dns

`

const out = "zcompare.go"

// copy zpack or whatever.
/*
func compare(a, b RR) int {
	switch x := a.(type) {
	case *CNAME:
		return x.compare(b)
	}
	return 0
}
*/

func main() {
	flag.Parse()
	specs, err := generate.StructTypeSpecs("types.go")
	if err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	b := &bytes.Buffer{}
	b.WriteString(hdr)

	for _, spec := range specs {
		rrname := spec.Name.Name
		if rrname == "APLPrefix" {
			continue
		}

		//
		// Compare functions, does compare(a, b RR) as a.compare(b)
		//

		fmt.Fprintf(b, "func (rr *%s) compare(b RR) (x int) {\n", rrname)

		strct := spec.Type.(*ast.StructType)
		for _, field := range strct.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			fieldname := field.Names[0].String()
			if fieldname == "Hdr" {
				continue
			}

			o := func(s string) { fmt.Fprintf(b, s+";if x != 0 { return x }\n", fieldname, rrname, fieldname) }
			// fieldtype is either slice or the actual singular type name.
			fieldtype := ""
			if id, ok := field.Type.(*ast.Ident); ok {
				fieldtype = id.Name
			}
			if _, ok := field.Type.(*ast.ArrayType); ok {
				fieldtype = "slice"
			}

			tag := ""
			if field.Tag != nil {
				tag = strings.Trim(field.Tag.Value, "`")
			}

			if fieldtype == "slice" {
				switch tag {
				case `dns:"-"`: // ignored
				case `dns:"txt"`:

				case `dns:"opt"`:

				case `dns:"nsec"`:

				case `dns:"pairs"`:

				case `dns:"domain-name"`:

				case `dns:"apl"`:

				}
				continue
			}

			// non-slice fields

			switch {
			case tag == `dns:"-"`: // ignored
			case tag == `dns:"cdomain-name"`:
				fallthrough
			case tag == `dns:"domain-name"`:
				o("x = CompareName(rr.%s, b.(*%s).%s)")
			case tag == `dns:"a"`:

			case tag == `dns:"aaaa"`:

			case tag == `dns:"uint48"`:

			case tag == `dns:"txt"`:

			case strings.HasPrefix(tag, `dns:"size-base32`): // size-base32 can be packed just like base32
				fallthrough
			case tag == `dns:"base32"`:

			case strings.HasPrefix(tag, `dns:"size-base64`): // size-base64 can be packed just like base64
				fallthrough
			case tag == `dns:"base64"`:

			case strings.HasPrefix(tag, `dns:"size-hex:SaltLength`):

			case strings.HasPrefix(tag, `dns:"size-hex`): // size-hex can be packed just like hex
				fallthrough
			case tag == `dns:"hex"`:

			case tag == `dns:"any"`:

			case tag == `dns:"octet"`:

			case tag == `dns:"ipsechost"` || tag == `dns:"amtrelayhost"`:

			case tag == "":
				switch fieldtype {
				case "uint8":

				case "uint16":

				case "uint32":

				case "uint64":

				case "string":
				}
			}
		}
		fmt.Fprint(b, "return 0\n}\n\n")
	}

	generate.Write(b, out)
}

// structMember will take a tag like dns:"size-base32:SaltLength" and return the last part of this string.
func structMember(s string) string {
	idx := strings.LastIndex(s, ":")
	return strings.TrimSuffix(s[idx+1:], `"`)
}

// structTag will take a tag like dns:"size-base32:SaltLength" and return base32.
func structTag(s string) string {
	s = strings.TrimPrefix(s, `dns:"size-`)
	s, _, _ = strings.Cut(s, ":")
	return s
}
