//go:build ignore

// copy_generate generates zcopy.go which houses all the Copy methods.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"log"
	"slices"
	"strings"

	"codeberg.org/miekg/dns"
	"codeberg.org/miekg/dns/internal/generate"
)

var skip = []string{""}

var hdr = `
// Code generated by "go run copy_generate.go"; DO NOT EDIT.

package dns

import "slices"
import "codeberg.org/miekg/dns/svcb"

`

const out = "zcopy.go"

func main() {
	flag.Parse()
	specs, err := generate.StructTypeSpecs("types.go")
	if err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	lspecs := len(specs)
	especs, err := generate.StructTypeSpecs("edns_types.go")
	if err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	dspecs, err := generate.StructTypeSpecs("dso_types.go")
	if err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	specs = append(specs, especs...)
	specs = append(specs, dspecs...)

	b := &bytes.Buffer{}
	b.WriteString(hdr)

	for i, spec := range specs {
		rrname := spec.Name.Name
		if slices.Contains(skip, rrname) {
			continue
		}

		fmt.Fprintf(b, "func (rr *%s) Copy() RR {\n", rrname)
		strct := spec.Type.(*ast.StructType)

		// an embedded type, need to be copied by using that type.
		// we detect these when the field name matches an rrtype
		// this only true for real rrs, not edns0 ones: ESU has URI field, that would be considered an RR.
		if len(strct.Fields.List) == 1 && i < lspecs {
			field := strct.Fields.List[0].Type.(*ast.Ident).String()
			if _, ok := dns.StringToType[field]; ok {
				// embeded
				fmt.Fprintf(b, "return &%s{*rr.%s.Copy().(*%s)}\n}\n", rrname, field, field)
				continue
			}
		}

		fmt.Fprintf(b, "return &%s{\n", rrname)
		if i < lspecs { // edns0 types dont' even have Hdr.
			fmt.Fprintf(b, "\trr.Hdr,\n")
		}

		for _, field := range strct.Fields.List {
			if len(field.Names) == 0 {
				continue
			}

			fieldname := field.Names[0].String()
			if fieldname == "Hdr" {
				continue
			}

			// fieldtype is either slice or the actual singular type name.
			fieldtype := ""
			if id, ok := field.Type.(*ast.Ident); ok {
				fieldtype = id.Name
			}
			if _, ok := field.Type.(*ast.ArrayType); ok {
				fieldtype = "slice"
			}

			tag := ""
			if field.Tag != nil {
				tag = strings.Trim(field.Tag.Value, "`")
			}

			o := func(s string) { fmt.Fprintf(b, s, fieldname) }

			if fieldtype == "slice" {
				switch tag {
				case `dns:"pairs"`:
					// create a function that returns the copied values
					// these pairs live in a subdir, which lowecased rrname, SVCB -> svbc
					// some fiddling here, to inject this name here, will keeping using o(...)
					// this should also work for DELEG in the future
					pkg := strings.ToLower(rrname)
					fn := `func() []` + pkg + `.Pair {
						pairs := make([]` + pkg + `.Pair, len(rr.%[1]s))
						for i, p := range rr.%[1]s {
							pairs[i] = p.Copy()
						}
						return pairs
						}()` + ",\n"
					o(fn)
					continue
				}

				o("slices.Clone(rr.%s),\n")
				continue
			}

			o("rr.%s,\n")

		}
		fmt.Fprint(b, "}\n}\n\n")
	}

	generate.Write(b, out)
}
