//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"log"

	"codeberg.org/miekg/dns/internal/generate"
)

var hdr = `
// Code generated by "go run rdata_generate.go"; DO NOT EDIT.

package dns

import "codeberg.org/miekg/dns/rdata"

`

const out = "zrdata.go"

func main() {
	flag.Parse()
	specs, err := generate.StructTypeSpecs("types.go")
	if err != nil {
		log.Fatalf("Failed to generate %s: %v", out, err)
	}
	b := &bytes.Buffer{}
	b.WriteString(hdr)
	b.WriteString(`// TypeToRDATA is a map of constructors for each RR type to set it's rdata.
var TypeToRDATA = map[uint16]func(RR, RDATA){
`)

	for _, spec := range specs {
		rrname := spec.Name.Name
		switch rrname {
		case "OPT":
			fallthrough
		case "RFC3597":
			continue
		}

		strct := spec.Type.(*ast.StructType)

		if generate.IsEmbedded(strct) {
			fmt.Fprintf(b, "Type%[2]s: func (rr RR, rd RDATA) {  rr.(*%[2]s).%[1]s.%[1]s = rd.(rdata.%[1]s) },\n", strct.Fields.List[0].Type, rrname)
			continue
		}
		if len(strct.Fields.List) == 1 { // Only header, no rdata
			fmt.Fprintf(b, "Type%s: func (rr RR, rd RDATA) { },\n", rrname)
			continue
		}
		fmt.Fprintf(b, "Type%s: func (rr RR, rd RDATA) { rr.(*%[1]s).%[1]s = rd.(rdata.%[1]s) },\n", rrname)

	}
	b.WriteString("}\n")
	generate.Write(b, out)
}
