// Code generated by "go run deepcopy_generate.go"; DO NOT EDIT.

package dns

import (
	"slices"

	"codeberg.org/miekg/dns/deleg"
	"codeberg.org/miekg/dns/svcb"
)

func (rr *NULL) Clone() RR {
	return &NULL{
		rr.Hdr,
		rr.Null,
	}
}

func (rr *NXNAME) Clone() RR {
	return &NXNAME{
		rr.Hdr,
	}
}

func (rr *CNAME) Clone() RR {
	return &CNAME{
		rr.Hdr,
		rr.Target,
	}
}

func (rr *HINFO) Clone() RR {
	return &HINFO{
		rr.Hdr,
		rr.Cpu,
		rr.Os,
	}
}

func (rr *MB) Clone() RR {
	return &MB{
		rr.Hdr,
		rr.Mb,
	}
}

func (rr *MG) Clone() RR {
	return &MG{
		rr.Hdr,
		rr.Mg,
	}
}

func (rr *MINFO) Clone() RR {
	return &MINFO{
		rr.Hdr,
		rr.Rmail,
		rr.Email,
	}
}

func (rr *MR) Clone() RR {
	return &MR{
		rr.Hdr,
		rr.Mr,
	}
}

func (rr *MF) Clone() RR {
	return &MF{
		rr.Hdr,
		rr.Mf,
	}
}

func (rr *MD) Clone() RR {
	return &MD{
		rr.Hdr,
		rr.Md,
	}
}

func (rr *MX) Clone() RR {
	return &MX{
		rr.Hdr,
		rr.Preference,
		rr.Mx,
	}
}

func (rr *AFSDB) Clone() RR {
	return &AFSDB{
		rr.Hdr,
		rr.Subtype,
		rr.Hostname,
	}
}

func (rr *X25) Clone() RR {
	return &X25{
		rr.Hdr,
		rr.PSDNAddress,
	}
}

func (rr *ISDN) Clone() RR {
	return &ISDN{
		rr.Hdr,
		rr.Address,
		rr.SubAddress,
	}
}

func (rr *RT) Clone() RR {
	return &RT{
		rr.Hdr,
		rr.Preference,
		rr.Host,
	}
}

func (rr *NS) Clone() RR {
	return &NS{
		rr.Hdr,
		rr.Ns,
	}
}

func (rr *PTR) Clone() RR {
	return &PTR{
		rr.Hdr,
		rr.Ptr,
	}
}

func (rr *RP) Clone() RR {
	return &RP{
		rr.Hdr,
		rr.Mbox,
		rr.Txt,
	}
}

func (rr *SOA) Clone() RR {
	return &SOA{
		rr.Hdr,
		rr.Ns,
		rr.Mbox,
		rr.Serial,
		rr.Refresh,
		rr.Retry,
		rr.Expire,
		rr.Minttl,
	}
}

func (rr *TXT) Clone() RR {
	return &TXT{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SPF) Clone() RR {
	return &SPF{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *AVC) Clone() RR {
	return &AVC{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SRV) Clone() RR {
	return &SRV{
		rr.Hdr,
		rr.Priority,
		rr.Weight,
		rr.Port,
		rr.Target,
	}
}

func (rr *NAPTR) Clone() RR {
	return &NAPTR{
		rr.Hdr,
		rr.Order,
		rr.Preference,
		rr.Flags,
		rr.Service,
		rr.Regexp,
		rr.Replacement,
	}
}

func (rr *CERT) Clone() RR {
	return &CERT{
		rr.Hdr,
		rr.Type,
		rr.KeyTag,
		rr.Algorithm,
		rr.Certificate,
	}
}

func (rr *DNAME) Clone() RR {
	return &DNAME{
		rr.Hdr,
		rr.Target,
	}
}

func (rr *A) Clone() RR {
	return &A{
		rr.Hdr,
		rr.A,
	}
}

func (rr *AAAA) Clone() RR {
	return &AAAA{
		rr.Hdr,
		rr.AAAA,
	}
}

func (rr *PX) Clone() RR {
	return &PX{
		rr.Hdr,
		rr.Preference,
		rr.Map822,
		rr.Mapx400,
	}
}

func (rr *GPOS) Clone() RR {
	return &GPOS{
		rr.Hdr,
		rr.Longitude,
		rr.Latitude,
		rr.Altitude,
	}
}

func (rr *LOC) Clone() RR {
	return &LOC{
		rr.Hdr,
		rr.Version,
		rr.Size,
		rr.HorizPre,
		rr.VertPre,
		rr.Latitude,
		rr.Longitude,
		rr.Altitude,
	}
}

func (rr *SIG) Clone() RR {
	return &SIG{*rr.RRSIG.Clone().(*RRSIG)}
}

func (rr *RRSIG) Clone() RR {
	return &RRSIG{
		rr.Hdr,
		rr.TypeCovered,
		rr.Algorithm,
		rr.Labels,
		rr.OrigTTL,
		rr.Expiration,
		rr.Inception,
		rr.KeyTag,
		rr.SignerName,
		rr.Signature,
	}
}

func (rr *NXT) Clone() RR {
	return &NXT{*rr.NSEC.Clone().(*NSEC)}
}

func (rr *NSEC) Clone() RR {
	return &NSEC{
		rr.Hdr,
		rr.NextDomain,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *DLV) Clone() RR {
	return &DLV{*rr.DS.Clone().(*DS)}
}

func (rr *CDS) Clone() RR {
	return &CDS{*rr.DS.Clone().(*DS)}
}

func (rr *DS) Clone() RR {
	return &DS{
		rr.Hdr,
		rr.KeyTag,
		rr.Algorithm,
		rr.DigestType,
		rr.Digest,
	}
}

func (rr *KX) Clone() RR {
	return &KX{
		rr.Hdr,
		rr.Preference,
		rr.Exchanger,
	}
}

func (rr *TA) Clone() RR {
	return &TA{
		rr.Hdr,
		rr.KeyTag,
		rr.Algorithm,
		rr.DigestType,
		rr.Digest,
	}
}

func (rr *TALINK) Clone() RR {
	return &TALINK{
		rr.Hdr,
		rr.PreviousName,
		rr.NextName,
	}
}

func (rr *SSHFP) Clone() RR {
	return &SSHFP{
		rr.Hdr,
		rr.Algorithm,
		rr.Type,
		rr.FingerPrint,
	}
}

func (rr *KEY) Clone() RR {
	return &KEY{*rr.DNSKEY.Clone().(*DNSKEY)}
}

func (rr *CDNSKEY) Clone() RR {
	return &CDNSKEY{*rr.DNSKEY.Clone().(*DNSKEY)}
}

func (rr *DNSKEY) Clone() RR {
	return &DNSKEY{
		rr.Hdr,
		rr.Flags,
		rr.Protocol,
		rr.Algorithm,
		rr.PublicKey,
	}
}

func (rr *RKEY) Clone() RR {
	return &RKEY{
		rr.Hdr,
		rr.Flags,
		rr.Protocol,
		rr.Algorithm,
		rr.PublicKey,
	}
}

func (rr *NSAPPTR) Clone() RR {
	return &NSAPPTR{
		rr.Hdr,
		rr.Ptr,
	}
}

func (rr *NSEC3) Clone() RR {
	return &NSEC3{
		rr.Hdr,
		rr.Hash,
		rr.Flags,
		rr.Iterations,
		rr.SaltLength,
		rr.Salt,
		rr.HashLength,
		rr.NextDomain,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *NSEC3PARAM) Clone() RR {
	return &NSEC3PARAM{
		rr.Hdr,
		rr.Hash,
		rr.Flags,
		rr.Iterations,
		rr.SaltLength,
		rr.Salt,
	}
}

func (rr *TKEY) Clone() RR {
	return &TKEY{
		rr.Hdr,
		rr.Algorithm,
		rr.Inception,
		rr.Expiration,
		rr.Mode,
		rr.Error,
		rr.KeySize,
		rr.Key,
		rr.OtherLen,
		rr.OtherData,
	}
}

func (rr *RFC3597) Clone() RR {
	return &RFC3597{
		rr.Hdr,
		rr.Rdata,
	}
}

func (rr *URI) Clone() RR {
	return &URI{
		rr.Hdr,
		rr.Priority,
		rr.Weight,
		rr.Target,
	}
}

func (rr *DHCID) Clone() RR {
	return &DHCID{
		rr.Hdr,
		rr.Digest,
	}
}

func (rr *TLSA) Clone() RR {
	return &TLSA{
		rr.Hdr,
		rr.Usage,
		rr.Selector,
		rr.MatchingType,
		rr.Certificate,
	}
}

func (rr *SMIMEA) Clone() RR {
	return &SMIMEA{
		rr.Hdr,
		rr.Usage,
		rr.Selector,
		rr.MatchingType,
		rr.Certificate,
	}
}

func (rr *HIP) Clone() RR {
	return &HIP{
		rr.Hdr,
		rr.HitLength,
		rr.PublicKeyAlgorithm,
		rr.PublicKeyLength,
		rr.Hit,
		rr.PublicKey,
		slices.Clone(rr.RendezvousServers),
	}
}

func (rr *NINFO) Clone() RR {
	return &NINFO{
		rr.Hdr,
		slices.Clone(rr.ZSData),
	}
}

func (rr *NID) Clone() RR {
	return &NID{
		rr.Hdr,
		rr.Preference,
		rr.NodeID,
	}
}

func (rr *L32) Clone() RR {
	return &L32{
		rr.Hdr,
		rr.Preference,
		rr.Locator32,
	}
}

func (rr *L64) Clone() RR {
	return &L64{
		rr.Hdr,
		rr.Preference,
		rr.Locator64,
	}
}

func (rr *LP) Clone() RR {
	return &LP{
		rr.Hdr,
		rr.Preference,
		rr.Fqdn,
	}
}

func (rr *EUI48) Clone() RR {
	return &EUI48{
		rr.Hdr,
		rr.Address,
	}
}

func (rr *EUI64) Clone() RR {
	return &EUI64{
		rr.Hdr,
		rr.Address,
	}
}

func (rr *CAA) Clone() RR {
	return &CAA{
		rr.Hdr,
		rr.Flag,
		rr.Tag,
		rr.Value,
	}
}

func (rr *UID) Clone() RR {
	return &UID{
		rr.Hdr,
		rr.Uid,
	}
}

func (rr *GID) Clone() RR {
	return &GID{
		rr.Hdr,
		rr.Gid,
	}
}

func (rr *UINFO) Clone() RR {
	return &UINFO{
		rr.Hdr,
		rr.Uinfo,
	}
}

func (rr *EID) Clone() RR {
	return &EID{
		rr.Hdr,
		rr.Endpoint,
	}
}

func (rr *NIMLOC) Clone() RR {
	return &NIMLOC{
		rr.Hdr,
		rr.Locator,
	}
}

func (rr *OPENPGPKEY) Clone() RR {
	return &OPENPGPKEY{
		rr.Hdr,
		rr.PublicKey,
	}
}

func (rr *CSYNC) Clone() RR {
	return &CSYNC{
		rr.Hdr,
		rr.Serial,
		rr.Flags,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *ZONEMD) Clone() RR {
	return &ZONEMD{
		rr.Hdr,
		rr.Serial,
		rr.Scheme,
		rr.Hash,
		rr.Digest,
	}
}

func (rr *OPT) Clone() RR {
	return &OPT{
		rr.Hdr,
		slices.Clone(rr.Options),
	}
}

func (rr *RESINFO) Clone() RR {
	return &RESINFO{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SVCB) Clone() RR {
	return &SVCB{
		rr.Hdr,
		rr.Priority,
		rr.Target,
		func() []svcb.Pair {
			pairs := make([]svcb.Pair, len(rr.Value))
			for i, p := range rr.Value {
				pairs[i] = p.Clone()
			}
			return pairs
		}(),
	}
}

func (rr *HTTPS) Clone() RR {
	return &HTTPS{*rr.SVCB.Clone().(*SVCB)}
}

func (rr *DELEG) Clone() RR {
	return &DELEG{
		rr.Hdr,
		func() []deleg.Info {
			infos := make([]deleg.Info, len(rr.Value))
			for i, p := range rr.Value {
				infos[i] = p.Clone()
			}
			return infos
		}(),
	}
}

func (rr *DELEGI) Clone() RR {
	return &DELEGI{*rr.DELEG.Clone().(*DELEG)}
}

func (rr *DSYNC) Clone() RR {
	return &DSYNC{
		rr.Hdr,
		rr.Type,
		rr.Scheme,
		rr.Port,
		rr.Target,
	}
}

func (rr *ANY) Clone() RR {
	return &ANY{
		rr.Hdr,
	}
}

func (rr *AXFR) Clone() RR {
	return &AXFR{
		rr.Hdr,
	}
}

func (rr *IXFR) Clone() RR {
	return &IXFR{
		rr.Hdr,
	}
}

func (rr *TSIG) Clone() RR {
	return &TSIG{
		rr.Hdr,
		rr.Algorithm,
		rr.TimeSigned,
		rr.Fudge,
		rr.MACSize,
		rr.MAC,
		rr.OrigID,
		rr.Error,
		rr.OtherLen,
		rr.OtherData,
	}
}

func (rr *LLQ) Clone() RR {
	return &LLQ{
		rr.Version,
		rr.Opcode,
		rr.Error,
		rr.ID,
		rr.LeaseLife,
	}
}

func (rr *REPORTING) Clone() RR {
	return &REPORTING{
		rr.AgentDomain,
	}
}

func (rr *COOKIE) Clone() RR {
	return &COOKIE{
		rr.Cookie,
	}
}

func (rr *NSID) Clone() RR {
	return &NSID{
		rr.Nsid,
	}
}

func (rr *PADDING) Clone() RR {
	return &PADDING{
		rr.Padding,
	}
}

func (rr *EXPIRE) Clone() RR {
	return &EXPIRE{
		rr.Expire,
	}
}

func (rr *DAU) Clone() RR {
	return &DAU{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *DHU) Clone() RR {
	return &DHU{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *N3U) Clone() RR {
	return &N3U{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *TCPKEEPALIVE) Clone() RR {
	return &TCPKEEPALIVE{
		rr.Timeout,
		rr.Length,
	}
}

func (rr *EDE) Clone() RR {
	return &EDE{
		rr.InfoCode,
		rr.ExtraText,
	}
}

func (rr *SUBNET) Clone() RR {
	return &SUBNET{
		rr.Family,
		rr.SourceNetmask,
		rr.SourceScope,
		rr.Address,
	}
}

func (rr *ESU) Clone() RR {
	return &ESU{
		rr.URI,
	}
}

func (rr *ZONEVERSION) Clone() RR {
	return &ZONEVERSION{
		rr.Labels,
		rr.Type,
		slices.Clone(rr.Version),
	}
}

func (rr *KEEPALIVE) Clone() RR {
	return &KEEPALIVE{
		rr.InactivityTimeout,
		rr.KeepAliveInterval,
	}
}
