// Code generated by "go run compare_generate.go"; DO NOT EDIT.

package dns

func (rr *NULL) compare(b RR) (x int) {
	return 0
}

func (rr *NXNAME) compare(b RR) (x int) {
	return 0
}

func (rr *CNAME) compare(b RR) (x int) {
	x = CompareName(rr.Target, b.(*CNAME).Target)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *HINFO) compare(b RR) (x int) {
	return 0
}

func (rr *MB) compare(b RR) (x int) {
	x = CompareName(rr.Mb, b.(*MB).Mb)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *MG) compare(b RR) (x int) {
	x = CompareName(rr.Mg, b.(*MG).Mg)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *MINFO) compare(b RR) (x int) {
	x = CompareName(rr.Rmail, b.(*MINFO).Rmail)
	if x != 0 {
		return x
	}
	x = CompareName(rr.Email, b.(*MINFO).Email)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *MR) compare(b RR) (x int) {
	x = CompareName(rr.Mr, b.(*MR).Mr)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *MF) compare(b RR) (x int) {
	x = CompareName(rr.Mf, b.(*MF).Mf)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *MD) compare(b RR) (x int) {
	x = CompareName(rr.Md, b.(*MD).Md)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *MX) compare(b RR) (x int) {
	x = CompareName(rr.Mx, b.(*MX).Mx)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *AFSDB) compare(b RR) (x int) {
	x = CompareName(rr.Hostname, b.(*AFSDB).Hostname)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *X25) compare(b RR) (x int) {
	return 0
}

func (rr *ISDN) compare(b RR) (x int) {
	return 0
}

func (rr *RT) compare(b RR) (x int) {
	x = CompareName(rr.Host, b.(*RT).Host)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *NS) compare(b RR) (x int) {
	x = CompareName(rr.Ns, b.(*NS).Ns)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *PTR) compare(b RR) (x int) {
	x = CompareName(rr.Ptr, b.(*PTR).Ptr)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *RP) compare(b RR) (x int) {
	x = CompareName(rr.Mbox, b.(*RP).Mbox)
	if x != 0 {
		return x
	}
	x = CompareName(rr.Txt, b.(*RP).Txt)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *SOA) compare(b RR) (x int) {
	x = CompareName(rr.Ns, b.(*SOA).Ns)
	if x != 0 {
		return x
	}
	x = CompareName(rr.Mbox, b.(*SOA).Mbox)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *TXT) compare(b RR) (x int) {
	return 0
}

func (rr *SPF) compare(b RR) (x int) {
	return 0
}

func (rr *AVC) compare(b RR) (x int) {
	return 0
}

func (rr *SRV) compare(b RR) (x int) {
	x = CompareName(rr.Target, b.(*SRV).Target)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *NAPTR) compare(b RR) (x int) {
	x = CompareName(rr.Replacement, b.(*NAPTR).Replacement)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *CERT) compare(b RR) (x int) {
	return 0
}

func (rr *DNAME) compare(b RR) (x int) {
	x = CompareName(rr.Target, b.(*DNAME).Target)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *A) compare(b RR) (x int) {
	return 0
}

func (rr *AAAA) compare(b RR) (x int) {
	return 0
}

func (rr *PX) compare(b RR) (x int) {
	x = CompareName(rr.Map822, b.(*PX).Map822)
	if x != 0 {
		return x
	}
	x = CompareName(rr.Mapx400, b.(*PX).Mapx400)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *GPOS) compare(b RR) (x int) {
	return 0
}

func (rr *LOC) compare(b RR) (x int) {
	return 0
}

func (rr *SIG) compare(b RR) (x int) {
	return 0
}

func (rr *RRSIG) compare(b RR) (x int) {
	x = CompareName(rr.SignerName, b.(*RRSIG).SignerName)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *NXT) compare(b RR) (x int) {
	return 0
}

func (rr *NSEC) compare(b RR) (x int) {
	x = CompareName(rr.NextDomain, b.(*NSEC).NextDomain)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *DLV) compare(b RR) (x int) {
	return 0
}

func (rr *CDS) compare(b RR) (x int) {
	return 0
}

func (rr *DS) compare(b RR) (x int) {
	return 0
}

func (rr *KX) compare(b RR) (x int) {
	x = CompareName(rr.Exchanger, b.(*KX).Exchanger)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *TA) compare(b RR) (x int) {
	return 0
}

func (rr *TALINK) compare(b RR) (x int) {
	x = CompareName(rr.PreviousName, b.(*TALINK).PreviousName)
	if x != 0 {
		return x
	}
	x = CompareName(rr.NextName, b.(*TALINK).NextName)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *SSHFP) compare(b RR) (x int) {
	return 0
}

func (rr *KEY) compare(b RR) (x int) {
	return 0
}

func (rr *CDNSKEY) compare(b RR) (x int) {
	return 0
}

func (rr *DNSKEY) compare(b RR) (x int) {
	return 0
}

func (rr *IPSECKEY) compare(b RR) (x int) {
	return 0
}

func (rr *AMTRELAY) compare(b RR) (x int) {
	return 0
}

func (rr *RKEY) compare(b RR) (x int) {
	return 0
}

func (rr *NSAPPTR) compare(b RR) (x int) {
	x = CompareName(rr.Ptr, b.(*NSAPPTR).Ptr)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *NSEC3) compare(b RR) (x int) {
	return 0
}

func (rr *NSEC3PARAM) compare(b RR) (x int) {
	return 0
}

func (rr *TKEY) compare(b RR) (x int) {
	x = CompareName(rr.Algorithm, b.(*TKEY).Algorithm)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *RFC3597) compare(b RR) (x int) {
	return 0
}

func (rr *URI) compare(b RR) (x int) {
	return 0
}

func (rr *DHCID) compare(b RR) (x int) {
	return 0
}

func (rr *TLSA) compare(b RR) (x int) {
	return 0
}

func (rr *SMIMEA) compare(b RR) (x int) {
	return 0
}

func (rr *HIP) compare(b RR) (x int) {
	return 0
}

func (rr *NINFO) compare(b RR) (x int) {
	return 0
}

func (rr *NID) compare(b RR) (x int) {
	return 0
}

func (rr *L32) compare(b RR) (x int) {
	return 0
}

func (rr *L64) compare(b RR) (x int) {
	return 0
}

func (rr *LP) compare(b RR) (x int) {
	x = CompareName(rr.Fqdn, b.(*LP).Fqdn)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *EUI48) compare(b RR) (x int) {
	return 0
}

func (rr *EUI64) compare(b RR) (x int) {
	return 0
}

func (rr *CAA) compare(b RR) (x int) {
	return 0
}

func (rr *UID) compare(b RR) (x int) {
	return 0
}

func (rr *GID) compare(b RR) (x int) {
	return 0
}

func (rr *UINFO) compare(b RR) (x int) {
	return 0
}

func (rr *EID) compare(b RR) (x int) {
	return 0
}

func (rr *NIMLOC) compare(b RR) (x int) {
	return 0
}

func (rr *OPENPGPKEY) compare(b RR) (x int) {
	return 0
}

func (rr *CSYNC) compare(b RR) (x int) {
	return 0
}

func (rr *ZONEMD) compare(b RR) (x int) {
	return 0
}

func (rr *OPT) compare(b RR) (x int) {
	return 0
}

func (rr *RESINFO) compare(b RR) (x int) {
	return 0
}

func (rr *APL) compare(b RR) (x int) {
	return 0
}

func (rr *SVCB) compare(b RR) (x int) {
	x = CompareName(rr.Target, b.(*SVCB).Target)
	if x != 0 {
		return x
	}
	return 0
}

func (rr *HTTPS) compare(b RR) (x int) {
	return 0
}

func (rr *ANY) compare(b RR) (x int) {
	return 0
}

func (rr *AXFR) compare(b RR) (x int) {
	return 0
}

func (rr *IXFR) compare(b RR) (x int) {
	return 0
}

func (rr *TSIG) compare(b RR) (x int) {
	x = CompareName(rr.Algorithm, b.(*TSIG).Algorithm)
	if x != 0 {
		return x
	}
	return 0
}
