// Code generated by "go run compare_generate.go"; DO NOT EDIT.

package dns

import (
	"bytes"
	"strings"
)

func compare(a, b RR) int {
	switch x := a.(type) {
	case *NULL:
		return x.compare(b)
	case *NXNAME:
		return x.compare(b)
	case *CNAME:
		return x.compare(b)
	case *HINFO:
		return x.compare(b)
	case *MB:
		return x.compare(b)
	case *MG:
		return x.compare(b)
	case *MINFO:
		return x.compare(b)
	case *MR:
		return x.compare(b)
	case *MF:
		return x.compare(b)
	case *MD:
		return x.compare(b)
	case *MX:
		return x.compare(b)
	case *AFSDB:
		return x.compare(b)
	case *X25:
		return x.compare(b)
	case *ISDN:
		return x.compare(b)
	case *RT:
		return x.compare(b)
	case *NS:
		return x.compare(b)
	case *PTR:
		return x.compare(b)
	case *RP:
		return x.compare(b)
	case *SOA:
		return x.compare(b)
	case *TXT:
		return x.compare(b)
	case *SPF:
		return x.compare(b)
	case *AVC:
		return x.compare(b)
	case *SRV:
		return x.compare(b)
	case *NAPTR:
		return x.compare(b)
	case *CERT:
		return x.compare(b)
	case *DNAME:
		return x.compare(b)
	case *A:
		return x.compare(b)
	case *AAAA:
		return x.compare(b)
	case *PX:
		return x.compare(b)
	case *GPOS:
		return x.compare(b)
	case *LOC:
		return x.compare(b)
	case *SIG:
		return x.compare(b)
	case *RRSIG:
		return x.compare(b)
	case *NXT:
		return x.compare(b)
	case *NSEC:
		return x.compare(b)
	case *DLV:
		return x.compare(b)
	case *CDS:
		return x.compare(b)
	case *DS:
		return x.compare(b)
	case *KX:
		return x.compare(b)
	case *TA:
		return x.compare(b)
	case *TALINK:
		return x.compare(b)
	case *SSHFP:
		return x.compare(b)
	case *KEY:
		return x.compare(b)
	case *CDNSKEY:
		return x.compare(b)
	case *DNSKEY:
		return x.compare(b)
	case *RKEY:
		return x.compare(b)
	case *NSAPPTR:
		return x.compare(b)
	case *NSEC3:
		return x.compare(b)
	case *NSEC3PARAM:
		return x.compare(b)
	case *TKEY:
		return x.compare(b)
	case *URI:
		return x.compare(b)
	case *DHCID:
		return x.compare(b)
	case *TLSA:
		return x.compare(b)
	case *SMIMEA:
		return x.compare(b)
	case *HIP:
		return x.compare(b)
	case *NINFO:
		return x.compare(b)
	case *NID:
		return x.compare(b)
	case *L32:
		return x.compare(b)
	case *L64:
		return x.compare(b)
	case *LP:
		return x.compare(b)
	case *EUI48:
		return x.compare(b)
	case *EUI64:
		return x.compare(b)
	case *CAA:
		return x.compare(b)
	case *UID:
		return x.compare(b)
	case *GID:
		return x.compare(b)
	case *UINFO:
		return x.compare(b)
	case *EID:
		return x.compare(b)
	case *NIMLOC:
		return x.compare(b)
	case *OPENPGPKEY:
		return x.compare(b)
	case *CSYNC:
		return x.compare(b)
	case *ZONEMD:
		return x.compare(b)
	case *OPT:
		return x.compare(b)
	case *RESINFO:
		return x.compare(b)
	case *SVCB:
		return x.compare(b)
	case *HTTPS:
		return x.compare(b)
	case *DELEG:
		return x.compare(b)
	case *DELEGI:
		return x.compare(b)
	case *DSYNC:
		return x.compare(b)
	case *ANY:
		return x.compare(b)
	case *AXFR:
		return x.compare(b)
	case *IXFR:
		return x.compare(b)
	case *TSIG:
		return x.compare(b)
	}
	// if here, we don't have the RR in our pkg, check if it does Packer.
	if x, ok := a.(Comparer); ok {
		// panic if !ok?
		return x.Compare(b)
	}
	return 0
}

func (rr *NULL) compare(b RR) (x int) {
	return 0
}

func (rr *NXNAME) compare(b RR) (x int) {
	return 0
}

func (rr *CNAME) compare(b RR) (x int) {
	x = CompareName(rr.Target, b.(*CNAME).Target)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *HINFO) compare(b RR) (x int) {
	x = strings.Compare(rr.Cpu, b.(*HINFO).Cpu)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Os, b.(*HINFO).Os)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *MB) compare(b RR) (x int) {
	x = CompareName(rr.Mb, b.(*MB).Mb)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *MG) compare(b RR) (x int) {
	x = CompareName(rr.Mg, b.(*MG).Mg)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *MINFO) compare(b RR) (x int) {
	x = CompareName(rr.Rmail, b.(*MINFO).Rmail)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Email, b.(*MINFO).Email)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *MR) compare(b RR) (x int) {
	x = CompareName(rr.Mr, b.(*MR).Mr)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *MF) compare(b RR) (x int) {
	x = CompareName(rr.Mf, b.(*MF).Mf)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *MD) compare(b RR) (x int) {
	x = CompareName(rr.Md, b.(*MD).Md)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *MX) compare(b RR) (x int) {
	x = int(rr.Preference) - int(b.(*MX).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Mx, b.(*MX).Mx)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *AFSDB) compare(b RR) (x int) {
	x = int(rr.Subtype) - int(b.(*AFSDB).Subtype)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Hostname, b.(*AFSDB).Hostname)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *X25) compare(b RR) (x int) {
	x = strings.Compare(rr.PSDNAddress, b.(*X25).PSDNAddress)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *ISDN) compare(b RR) (x int) {
	x = strings.Compare(rr.Address, b.(*ISDN).Address)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.SubAddress, b.(*ISDN).SubAddress)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *RT) compare(b RR) (x int) {
	x = int(rr.Preference) - int(b.(*RT).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Host, b.(*RT).Host)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NS) compare(b RR) (x int) {
	x = CompareName(rr.Ns, b.(*NS).Ns)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *PTR) compare(b RR) (x int) {
	x = CompareName(rr.Ptr, b.(*PTR).Ptr)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *RP) compare(b RR) (x int) {
	x = CompareName(rr.Mbox, b.(*RP).Mbox)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Txt, b.(*RP).Txt)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *SOA) compare(b RR) (x int) {
	x = CompareName(rr.Ns, b.(*SOA).Ns)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Mbox, b.(*SOA).Mbox)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Serial) - int(b.(*SOA).Serial)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Refresh) - int(b.(*SOA).Refresh)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Retry) - int(b.(*SOA).Retry)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Expire) - int(b.(*SOA).Expire)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Minttl) - int(b.(*SOA).Minttl)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *TXT) compare(b RR) (x int) {
	j := 0
	for i := range rr.Txt {
		if i > j || x != 0 {
			break
		}
		x = strings.Compare(rr.Txt[i], b.(*TXT).Txt[j])
		j++
	}
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *SPF) compare(b RR) (x int) {
	j := 0
	for i := range rr.Txt {
		if i > j || x != 0 {
			break
		}
		x = strings.Compare(rr.Txt[i], b.(*SPF).Txt[j])
		j++
	}
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *AVC) compare(b RR) (x int) {
	j := 0
	for i := range rr.Txt {
		if i > j || x != 0 {
			break
		}
		x = strings.Compare(rr.Txt[i], b.(*AVC).Txt[j])
		j++
	}
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *SRV) compare(b RR) (x int) {
	x = int(rr.Priority) - int(b.(*SRV).Priority)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Weight) - int(b.(*SRV).Weight)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Port) - int(b.(*SRV).Port)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Target, b.(*SRV).Target)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NAPTR) compare(b RR) (x int) {
	x = int(rr.Order) - int(b.(*NAPTR).Order)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Preference) - int(b.(*NAPTR).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Flags, b.(*NAPTR).Flags)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Service, b.(*NAPTR).Service)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Regexp, b.(*NAPTR).Regexp)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Replacement, b.(*NAPTR).Replacement)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *CERT) compare(b RR) (x int) {
	x = int(rr.Type) - int(b.(*CERT).Type)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.KeyTag) - int(b.(*CERT).KeyTag)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Algorithm) - int(b.(*CERT).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Certificate, b.(*CERT).Certificate)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *DNAME) compare(b RR) (x int) {
	x = CompareName(rr.Target, b.(*DNAME).Target)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *A) compare(b RR) (x int) {
	x = bytes.Compare(rr.A, b.(*A).A)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *AAAA) compare(b RR) (x int) {
	x = bytes.Compare(rr.AAAA, b.(*AAAA).AAAA)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *PX) compare(b RR) (x int) {
	x = int(rr.Preference) - int(b.(*PX).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Map822, b.(*PX).Map822)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Mapx400, b.(*PX).Mapx400)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *GPOS) compare(b RR) (x int) {
	x = strings.Compare(rr.Longitude, b.(*GPOS).Longitude)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Latitude, b.(*GPOS).Latitude)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Altitude, b.(*GPOS).Altitude)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *LOC) compare(b RR) (x int) {
	x = int(rr.Version) - int(b.(*LOC).Version)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Size) - int(b.(*LOC).Size)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.HorizPre) - int(b.(*LOC).HorizPre)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.VertPre) - int(b.(*LOC).VertPre)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Latitude) - int(b.(*LOC).Latitude)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Longitude) - int(b.(*LOC).Longitude)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Altitude) - int(b.(*LOC).Altitude)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *SIG) compare(b RR) (x int) {
	return rr.RRSIG.compare(&b.(*SIG).RRSIG)
}

func (rr *RRSIG) compare(b RR) (x int) {
	x = int(rr.TypeCovered) - int(b.(*RRSIG).TypeCovered)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Algorithm) - int(b.(*RRSIG).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Labels) - int(b.(*RRSIG).Labels)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.OrigTTL) - int(b.(*RRSIG).OrigTTL)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Expiration) - int(b.(*RRSIG).Expiration)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Inception) - int(b.(*RRSIG).Inception)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.KeyTag) - int(b.(*RRSIG).KeyTag)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.SignerName, b.(*RRSIG).SignerName)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Signature, b.(*RRSIG).Signature)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NXT) compare(b RR) (x int) {
	return rr.NSEC.compare(&b.(*NXT).NSEC)
}

func (rr *NSEC) compare(b RR) (x int) {
	x = CompareName(rr.NextDomain, b.(*NSEC).NextDomain)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *DLV) compare(b RR) (x int) {
	return rr.DS.compare(&b.(*DLV).DS)
}

func (rr *CDS) compare(b RR) (x int) {
	return rr.DS.compare(&b.(*CDS).DS)
}

func (rr *DS) compare(b RR) (x int) {
	x = int(rr.KeyTag) - int(b.(*DS).KeyTag)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Algorithm) - int(b.(*DS).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.DigestType) - int(b.(*DS).DigestType)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Digest, b.(*DS).Digest)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *KX) compare(b RR) (x int) {
	x = int(rr.Preference) - int(b.(*KX).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Exchanger, b.(*KX).Exchanger)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *TA) compare(b RR) (x int) {
	x = int(rr.KeyTag) - int(b.(*TA).KeyTag)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Algorithm) - int(b.(*TA).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.DigestType) - int(b.(*TA).DigestType)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Digest, b.(*TA).Digest)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *TALINK) compare(b RR) (x int) {
	x = CompareName(rr.PreviousName, b.(*TALINK).PreviousName)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.NextName, b.(*TALINK).NextName)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *SSHFP) compare(b RR) (x int) {
	x = int(rr.Algorithm) - int(b.(*SSHFP).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Type) - int(b.(*SSHFP).Type)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.FingerPrint, b.(*SSHFP).FingerPrint)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *KEY) compare(b RR) (x int) {
	return rr.DNSKEY.compare(&b.(*KEY).DNSKEY)
}

func (rr *CDNSKEY) compare(b RR) (x int) {
	return rr.DNSKEY.compare(&b.(*CDNSKEY).DNSKEY)
}

func (rr *DNSKEY) compare(b RR) (x int) {
	x = int(rr.Flags) - int(b.(*DNSKEY).Flags)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Protocol) - int(b.(*DNSKEY).Protocol)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Algorithm) - int(b.(*DNSKEY).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.PublicKey, b.(*DNSKEY).PublicKey)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *RKEY) compare(b RR) (x int) {
	x = int(rr.Flags) - int(b.(*RKEY).Flags)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Protocol) - int(b.(*RKEY).Protocol)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Algorithm) - int(b.(*RKEY).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.PublicKey, b.(*RKEY).PublicKey)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NSAPPTR) compare(b RR) (x int) {
	x = CompareName(rr.Ptr, b.(*NSAPPTR).Ptr)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NSEC3) compare(b RR) (x int) {
	x = int(rr.Hash) - int(b.(*NSEC3).Hash)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Flags) - int(b.(*NSEC3).Flags)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Iterations) - int(b.(*NSEC3).Iterations)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.SaltLength) - int(b.(*NSEC3).SaltLength)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Salt, b.(*NSEC3).Salt)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.HashLength) - int(b.(*NSEC3).HashLength)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.NextDomain, b.(*NSEC3).NextDomain)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NSEC3PARAM) compare(b RR) (x int) {
	x = int(rr.Hash) - int(b.(*NSEC3PARAM).Hash)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Flags) - int(b.(*NSEC3PARAM).Flags)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Iterations) - int(b.(*NSEC3PARAM).Iterations)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.SaltLength) - int(b.(*NSEC3PARAM).SaltLength)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Salt, b.(*NSEC3PARAM).Salt)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *TKEY) compare(b RR) (x int) {
	x = CompareName(rr.Algorithm, b.(*TKEY).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Inception) - int(b.(*TKEY).Inception)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Expiration) - int(b.(*TKEY).Expiration)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Mode) - int(b.(*TKEY).Mode)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Error) - int(b.(*TKEY).Error)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.KeySize) - int(b.(*TKEY).KeySize)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Key, b.(*TKEY).Key)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.OtherLen) - int(b.(*TKEY).OtherLen)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.OtherData, b.(*TKEY).OtherData)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *RFC3597) compare(b RR) (x int) {
	x = strings.Compare(rr.Rdata, b.(*RFC3597).Rdata)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *URI) compare(b RR) (x int) {
	x = int(rr.Priority) - int(b.(*URI).Priority)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Weight) - int(b.(*URI).Weight)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *DHCID) compare(b RR) (x int) {
	x = strings.Compare(rr.Digest, b.(*DHCID).Digest)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *TLSA) compare(b RR) (x int) {
	x = int(rr.Usage) - int(b.(*TLSA).Usage)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Selector) - int(b.(*TLSA).Selector)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.MatchingType) - int(b.(*TLSA).MatchingType)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Certificate, b.(*TLSA).Certificate)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *SMIMEA) compare(b RR) (x int) {
	x = int(rr.Usage) - int(b.(*SMIMEA).Usage)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Selector) - int(b.(*SMIMEA).Selector)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.MatchingType) - int(b.(*SMIMEA).MatchingType)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Certificate, b.(*SMIMEA).Certificate)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *HIP) compare(b RR) (x int) {
	x = int(rr.HitLength) - int(b.(*HIP).HitLength)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.PublicKeyAlgorithm) - int(b.(*HIP).PublicKeyAlgorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.PublicKeyLength) - int(b.(*HIP).PublicKeyLength)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Hit, b.(*HIP).Hit)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.PublicKey, b.(*HIP).PublicKey)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NINFO) compare(b RR) (x int) {
	j := 0
	for i := range rr.ZSData {
		if i > j || x != 0 {
			break
		}
		x = strings.Compare(rr.ZSData[i], b.(*NINFO).ZSData[j])
		j++
	}
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NID) compare(b RR) (x int) {
	x = int(rr.Preference) - int(b.(*NID).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.NodeID) - int(b.(*NID).NodeID)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *L32) compare(b RR) (x int) {
	x = int(rr.Preference) - int(b.(*L32).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = bytes.Compare(rr.Locator32, b.(*L32).Locator32)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *L64) compare(b RR) (x int) {
	x = int(rr.Preference) - int(b.(*L64).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Locator64) - int(b.(*L64).Locator64)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *LP) compare(b RR) (x int) {
	x = int(rr.Preference) - int(b.(*LP).Preference)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Fqdn, b.(*LP).Fqdn)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *EUI48) compare(b RR) (x int) {
	x = int(rr.Address) - int(b.(*EUI48).Address)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *EUI64) compare(b RR) (x int) {
	x = int(rr.Address) - int(b.(*EUI64).Address)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *CAA) compare(b RR) (x int) {
	x = int(rr.Flag) - int(b.(*CAA).Flag)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Tag, b.(*CAA).Tag)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *UID) compare(b RR) (x int) {
	x = int(rr.Uid) - int(b.(*UID).Uid)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *GID) compare(b RR) (x int) {
	x = int(rr.Gid) - int(b.(*GID).Gid)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *UINFO) compare(b RR) (x int) {
	x = strings.Compare(rr.Uinfo, b.(*UINFO).Uinfo)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *EID) compare(b RR) (x int) {
	x = strings.Compare(rr.Endpoint, b.(*EID).Endpoint)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *NIMLOC) compare(b RR) (x int) {
	x = strings.Compare(rr.Locator, b.(*NIMLOC).Locator)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *OPENPGPKEY) compare(b RR) (x int) {
	x = strings.Compare(rr.PublicKey, b.(*OPENPGPKEY).PublicKey)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *CSYNC) compare(b RR) (x int) {
	x = int(rr.Serial) - int(b.(*CSYNC).Serial)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Flags) - int(b.(*CSYNC).Flags)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *ZONEMD) compare(b RR) (x int) {
	x = int(rr.Serial) - int(b.(*ZONEMD).Serial)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Scheme) - int(b.(*ZONEMD).Scheme)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Hash) - int(b.(*ZONEMD).Hash)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.Digest, b.(*ZONEMD).Digest)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *OPT) compare(b RR) (x int) {
	return 0
}

func (rr *RESINFO) compare(b RR) (x int) {
	j := 0
	for i := range rr.Txt {
		if i > j || x != 0 {
			break
		}
		x = strings.Compare(rr.Txt[i], b.(*RESINFO).Txt[j])
		j++
	}
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *SVCB) compare(b RR) (x int) {
	x = int(rr.Priority) - int(b.(*SVCB).Priority)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Target, b.(*SVCB).Target)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *HTTPS) compare(b RR) (x int) {
	return rr.SVCB.compare(&b.(*HTTPS).SVCB)
}

func (rr *DELEG) compare(b RR) (x int) {
	return 0
}

func (rr *DELEGI) compare(b RR) (x int) {
	return rr.DELEG.compare(&b.(*DELEGI).DELEG)
}

func (rr *DSYNC) compare(b RR) (x int) {
	x = int(rr.Type) - int(b.(*DSYNC).Type)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Scheme) - int(b.(*DSYNC).Scheme)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Port) - int(b.(*DSYNC).Port)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = CompareName(rr.Target, b.(*DSYNC).Target)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}

func (rr *ANY) compare(b RR) (x int) {
	return 0
}

func (rr *AXFR) compare(b RR) (x int) {
	return 0
}

func (rr *IXFR) compare(b RR) (x int) {
	return 0
}

func (rr *TSIG) compare(b RR) (x int) {
	x = CompareName(rr.Algorithm, b.(*TSIG).Algorithm)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.TimeSigned) - int(b.(*TSIG).TimeSigned)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Fudge) - int(b.(*TSIG).Fudge)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.MACSize) - int(b.(*TSIG).MACSize)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.MAC, b.(*TSIG).MAC)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.OrigID) - int(b.(*TSIG).OrigID)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.Error) - int(b.(*TSIG).Error)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = int(rr.OtherLen) - int(b.(*TSIG).OtherLen)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	x = strings.Compare(rr.OtherData, b.(*TSIG).OtherData)
	if x != 0 {
		if x < 0 {
			return -1
		}
		return 1
	}
	return 0
}
