// Code generated by "go run copy_generate.go"; DO NOT EDIT.

package dns

import (
	"codeberg.org/miekg/dns/deleg"
	"codeberg.org/miekg/dns/svcb"
	"slices"
)

func (rr *NULL) Copy() RR {
	return &NULL{
		rr.Hdr,
		rr.Null,
	}
}

func (rr *NXNAME) Copy() RR {
	return &NXNAME{
		rr.Hdr,
	}
}

func (rr *CNAME) Copy() RR {
	return &CNAME{
		rr.Hdr,
		rr.Target,
	}
}

func (rr *HINFO) Copy() RR {
	return &HINFO{
		rr.Hdr,
		rr.Cpu,
		rr.Os,
	}
}

func (rr *MB) Copy() RR {
	return &MB{
		rr.Hdr,
		rr.Mb,
	}
}

func (rr *MG) Copy() RR {
	return &MG{
		rr.Hdr,
		rr.Mg,
	}
}

func (rr *MINFO) Copy() RR {
	return &MINFO{
		rr.Hdr,
		rr.Rmail,
		rr.Email,
	}
}

func (rr *MR) Copy() RR {
	return &MR{
		rr.Hdr,
		rr.Mr,
	}
}

func (rr *MF) Copy() RR {
	return &MF{
		rr.Hdr,
		rr.Mf,
	}
}

func (rr *MD) Copy() RR {
	return &MD{
		rr.Hdr,
		rr.Md,
	}
}

func (rr *MX) Copy() RR {
	return &MX{
		rr.Hdr,
		rr.Preference,
		rr.Mx,
	}
}

func (rr *AFSDB) Copy() RR {
	return &AFSDB{
		rr.Hdr,
		rr.Subtype,
		rr.Hostname,
	}
}

func (rr *X25) Copy() RR {
	return &X25{
		rr.Hdr,
		rr.PSDNAddress,
	}
}

func (rr *ISDN) Copy() RR {
	return &ISDN{
		rr.Hdr,
		rr.Address,
		rr.SubAddress,
	}
}

func (rr *RT) Copy() RR {
	return &RT{
		rr.Hdr,
		rr.Preference,
		rr.Host,
	}
}

func (rr *NS) Copy() RR {
	return &NS{
		rr.Hdr,
		rr.Ns,
	}
}

func (rr *PTR) Copy() RR {
	return &PTR{
		rr.Hdr,
		rr.Ptr,
	}
}

func (rr *RP) Copy() RR {
	return &RP{
		rr.Hdr,
		rr.Mbox,
		rr.Txt,
	}
}

func (rr *SOA) Copy() RR {
	return &SOA{
		rr.Hdr,
		rr.Ns,
		rr.Mbox,
		rr.Serial,
		rr.Refresh,
		rr.Retry,
		rr.Expire,
		rr.Minttl,
	}
}

func (rr *TXT) Copy() RR {
	return &TXT{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SPF) Copy() RR {
	return &SPF{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *AVC) Copy() RR {
	return &AVC{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SRV) Copy() RR {
	return &SRV{
		rr.Hdr,
		rr.Priority,
		rr.Weight,
		rr.Port,
		rr.Target,
	}
}

func (rr *NAPTR) Copy() RR {
	return &NAPTR{
		rr.Hdr,
		rr.Order,
		rr.Preference,
		rr.Flags,
		rr.Service,
		rr.Regexp,
		rr.Replacement,
	}
}

func (rr *CERT) Copy() RR {
	return &CERT{
		rr.Hdr,
		rr.Type,
		rr.KeyTag,
		rr.Algorithm,
		rr.Certificate,
	}
}

func (rr *DNAME) Copy() RR {
	return &DNAME{
		rr.Hdr,
		rr.Target,
	}
}

func (rr *A) Copy() RR {
	return &A{
		rr.Hdr,
		rr.A,
	}
}

func (rr *AAAA) Copy() RR {
	return &AAAA{
		rr.Hdr,
		rr.AAAA,
	}
}

func (rr *PX) Copy() RR {
	return &PX{
		rr.Hdr,
		rr.Preference,
		rr.Map822,
		rr.Mapx400,
	}
}

func (rr *GPOS) Copy() RR {
	return &GPOS{
		rr.Hdr,
		rr.Longitude,
		rr.Latitude,
		rr.Altitude,
	}
}

func (rr *LOC) Copy() RR {
	return &LOC{
		rr.Hdr,
		rr.Version,
		rr.Size,
		rr.HorizPre,
		rr.VertPre,
		rr.Latitude,
		rr.Longitude,
		rr.Altitude,
	}
}

func (rr *SIG) Copy() RR {
	return &SIG{*rr.RRSIG.Copy().(*RRSIG)}
}
func (rr *RRSIG) Copy() RR {
	return &RRSIG{
		rr.Hdr,
		rr.TypeCovered,
		rr.Algorithm,
		rr.Labels,
		rr.OrigTTL,
		rr.Expiration,
		rr.Inception,
		rr.KeyTag,
		rr.SignerName,
		rr.Signature,
	}
}

func (rr *NXT) Copy() RR {
	return &NXT{*rr.NSEC.Copy().(*NSEC)}
}
func (rr *NSEC) Copy() RR {
	return &NSEC{
		rr.Hdr,
		rr.NextDomain,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *DLV) Copy() RR {
	return &DLV{*rr.DS.Copy().(*DS)}
}
func (rr *CDS) Copy() RR {
	return &CDS{*rr.DS.Copy().(*DS)}
}
func (rr *DS) Copy() RR {
	return &DS{
		rr.Hdr,
		rr.KeyTag,
		rr.Algorithm,
		rr.DigestType,
		rr.Digest,
	}
}

func (rr *KX) Copy() RR {
	return &KX{
		rr.Hdr,
		rr.Preference,
		rr.Exchanger,
	}
}

func (rr *TA) Copy() RR {
	return &TA{
		rr.Hdr,
		rr.KeyTag,
		rr.Algorithm,
		rr.DigestType,
		rr.Digest,
	}
}

func (rr *TALINK) Copy() RR {
	return &TALINK{
		rr.Hdr,
		rr.PreviousName,
		rr.NextName,
	}
}

func (rr *SSHFP) Copy() RR {
	return &SSHFP{
		rr.Hdr,
		rr.Algorithm,
		rr.Type,
		rr.FingerPrint,
	}
}

func (rr *KEY) Copy() RR {
	return &KEY{*rr.DNSKEY.Copy().(*DNSKEY)}
}
func (rr *CDNSKEY) Copy() RR {
	return &CDNSKEY{*rr.DNSKEY.Copy().(*DNSKEY)}
}
func (rr *DNSKEY) Copy() RR {
	return &DNSKEY{
		rr.Hdr,
		rr.Flags,
		rr.Protocol,
		rr.Algorithm,
		rr.PublicKey,
	}
}

func (rr *RKEY) Copy() RR {
	return &RKEY{
		rr.Hdr,
		rr.Flags,
		rr.Protocol,
		rr.Algorithm,
		rr.PublicKey,
	}
}

func (rr *NSAPPTR) Copy() RR {
	return &NSAPPTR{
		rr.Hdr,
		rr.Ptr,
	}
}

func (rr *NSEC3) Copy() RR {
	return &NSEC3{
		rr.Hdr,
		rr.Hash,
		rr.Flags,
		rr.Iterations,
		rr.SaltLength,
		rr.Salt,
		rr.HashLength,
		rr.NextDomain,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *NSEC3PARAM) Copy() RR {
	return &NSEC3PARAM{
		rr.Hdr,
		rr.Hash,
		rr.Flags,
		rr.Iterations,
		rr.SaltLength,
		rr.Salt,
	}
}

func (rr *TKEY) Copy() RR {
	return &TKEY{
		rr.Hdr,
		rr.Algorithm,
		rr.Inception,
		rr.Expiration,
		rr.Mode,
		rr.Error,
		rr.KeySize,
		rr.Key,
		rr.OtherLen,
		rr.OtherData,
	}
}

func (rr *RFC3597) Copy() RR {
	return &RFC3597{
		rr.Hdr,
		rr.Rdata,
	}
}

func (rr *URI) Copy() RR {
	return &URI{
		rr.Hdr,
		rr.Priority,
		rr.Weight,
		rr.Target,
	}
}

func (rr *DHCID) Copy() RR {
	return &DHCID{
		rr.Hdr,
		rr.Digest,
	}
}

func (rr *TLSA) Copy() RR {
	return &TLSA{
		rr.Hdr,
		rr.Usage,
		rr.Selector,
		rr.MatchingType,
		rr.Certificate,
	}
}

func (rr *SMIMEA) Copy() RR {
	return &SMIMEA{
		rr.Hdr,
		rr.Usage,
		rr.Selector,
		rr.MatchingType,
		rr.Certificate,
	}
}

func (rr *HIP) Copy() RR {
	return &HIP{
		rr.Hdr,
		rr.HitLength,
		rr.PublicKeyAlgorithm,
		rr.PublicKeyLength,
		rr.Hit,
		rr.PublicKey,
		slices.Clone(rr.RendezvousServers),
	}
}

func (rr *NINFO) Copy() RR {
	return &NINFO{
		rr.Hdr,
		slices.Clone(rr.ZSData),
	}
}

func (rr *NID) Copy() RR {
	return &NID{
		rr.Hdr,
		rr.Preference,
		rr.NodeID,
	}
}

func (rr *L32) Copy() RR {
	return &L32{
		rr.Hdr,
		rr.Preference,
		rr.Locator32,
	}
}

func (rr *L64) Copy() RR {
	return &L64{
		rr.Hdr,
		rr.Preference,
		rr.Locator64,
	}
}

func (rr *LP) Copy() RR {
	return &LP{
		rr.Hdr,
		rr.Preference,
		rr.Fqdn,
	}
}

func (rr *EUI48) Copy() RR {
	return &EUI48{
		rr.Hdr,
		rr.Address,
	}
}

func (rr *EUI64) Copy() RR {
	return &EUI64{
		rr.Hdr,
		rr.Address,
	}
}

func (rr *CAA) Copy() RR {
	return &CAA{
		rr.Hdr,
		rr.Flag,
		rr.Tag,
		rr.Value,
	}
}

func (rr *UID) Copy() RR {
	return &UID{
		rr.Hdr,
		rr.Uid,
	}
}

func (rr *GID) Copy() RR {
	return &GID{
		rr.Hdr,
		rr.Gid,
	}
}

func (rr *UINFO) Copy() RR {
	return &UINFO{
		rr.Hdr,
		rr.Uinfo,
	}
}

func (rr *EID) Copy() RR {
	return &EID{
		rr.Hdr,
		rr.Endpoint,
	}
}

func (rr *NIMLOC) Copy() RR {
	return &NIMLOC{
		rr.Hdr,
		rr.Locator,
	}
}

func (rr *OPENPGPKEY) Copy() RR {
	return &OPENPGPKEY{
		rr.Hdr,
		rr.PublicKey,
	}
}

func (rr *CSYNC) Copy() RR {
	return &CSYNC{
		rr.Hdr,
		rr.Serial,
		rr.Flags,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *ZONEMD) Copy() RR {
	return &ZONEMD{
		rr.Hdr,
		rr.Serial,
		rr.Scheme,
		rr.Hash,
		rr.Digest,
	}
}

func (rr *OPT) Copy() RR {
	return &OPT{
		rr.Hdr,
		slices.Clone(rr.Options),
	}
}

func (rr *RESINFO) Copy() RR {
	return &RESINFO{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SVCB) Copy() RR {
	return &SVCB{
		rr.Hdr,
		rr.Priority,
		rr.Target,
		func() []svcb.Pair {
			pairs := make([]svcb.Pair, len(rr.Value))
			for i, p := range rr.Value {
				pairs[i] = p.Copy()
			}
			return pairs
		}(),
	}
}

func (rr *HTTPS) Copy() RR {
	return &HTTPS{*rr.SVCB.Copy().(*SVCB)}
}
func (rr *DELEG) Copy() RR {
	return &DELEG{
		rr.Hdr,
		func() []deleg.Info {
			infos := make([]deleg.Info, len(rr.Value))
			for i, p := range rr.Value {
				infos[i] = p.Copy()
			}
			return infos
		}(),
	}
}

func (rr *DELEGI) Copy() RR {
	return &DELEGI{*rr.DELEG.Copy().(*DELEG)}
}
func (rr *ANY) Copy() RR {
	return &ANY{
		rr.Hdr,
	}
}

func (rr *AXFR) Copy() RR {
	return &AXFR{
		rr.Hdr,
	}
}

func (rr *IXFR) Copy() RR {
	return &IXFR{
		rr.Hdr,
	}
}

func (rr *TSIG) Copy() RR {
	return &TSIG{
		rr.Hdr,
		rr.Algorithm,
		rr.TimeSigned,
		rr.Fudge,
		rr.MACSize,
		rr.MAC,
		rr.OrigID,
		rr.Error,
		rr.OtherLen,
		rr.OtherData,
	}
}

func (rr *LLQ) Copy() RR {
	return &LLQ{
		rr.Version,
		rr.Opcode,
		rr.Error,
		rr.ID,
		rr.LeaseLife,
	}
}

func (rr *REPORTING) Copy() RR {
	return &REPORTING{
		rr.AgentDomain,
	}
}

func (rr *COOKIE) Copy() RR {
	return &COOKIE{
		rr.Cookie,
	}
}

func (rr *NSID) Copy() RR {
	return &NSID{
		rr.Nsid,
	}
}

func (rr *PADDING) Copy() RR {
	return &PADDING{
		rr.Padding,
	}
}

func (rr *EXPIRE) Copy() RR {
	return &EXPIRE{
		rr.Expire,
	}
}

func (rr *DAU) Copy() RR {
	return &DAU{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *DHU) Copy() RR {
	return &DHU{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *N3U) Copy() RR {
	return &N3U{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *TCPKEEPALIVE) Copy() RR {
	return &TCPKEEPALIVE{
		rr.Timeout,
		rr.Length,
	}
}

func (rr *EDE) Copy() RR {
	return &EDE{
		rr.InfoCode,
		rr.ExtraText,
	}
}

func (rr *SUBNET) Copy() RR {
	return &SUBNET{
		rr.Family,
		rr.SourceNetmask,
		rr.SourceScope,
		rr.Address,
	}
}

func (rr *ESU) Copy() RR {
	return &ESU{
		rr.URI,
	}
}

func (rr *ZONEVERSION) Copy() RR {
	return &ZONEVERSION{
		rr.Labels,
		rr.Type,
		slices.Clone(rr.Version),
	}
}

func (rr *KEEPALIVE) Copy() RR {
	return &KEEPALIVE{
		rr.InactivityTimeout,
		rr.KeepAliveInterval,
	}
}
