// Code generated by "go run deepcopy_generate.go"; DO NOT EDIT.

package dns

import (
	"codeberg.org/miekg/dns/deleg"
	"codeberg.org/miekg/dns/svcb"
	"slices"
)

func (rr *NULL) DeepCopy() RR {
	return &NULL{
		rr.Hdr,
		rr.Null,
	}
}

func (rr *NXNAME) DeepCopy() RR {
	return &NXNAME{
		rr.Hdr,
	}
}

func (rr *CNAME) DeepCopy() RR {
	return &CNAME{
		rr.Hdr,
		rr.Target,
	}
}

func (rr *HINFO) DeepCopy() RR {
	return &HINFO{
		rr.Hdr,
		rr.Cpu,
		rr.Os,
	}
}

func (rr *MB) DeepCopy() RR {
	return &MB{
		rr.Hdr,
		rr.Mb,
	}
}

func (rr *MG) DeepCopy() RR {
	return &MG{
		rr.Hdr,
		rr.Mg,
	}
}

func (rr *MINFO) DeepCopy() RR {
	return &MINFO{
		rr.Hdr,
		rr.Rmail,
		rr.Email,
	}
}

func (rr *MR) DeepCopy() RR {
	return &MR{
		rr.Hdr,
		rr.Mr,
	}
}

func (rr *MF) DeepCopy() RR {
	return &MF{
		rr.Hdr,
		rr.Mf,
	}
}

func (rr *MD) DeepCopy() RR {
	return &MD{
		rr.Hdr,
		rr.Md,
	}
}

func (rr *MX) DeepCopy() RR {
	return &MX{
		rr.Hdr,
		rr.Preference,
		rr.Mx,
	}
}

func (rr *AFSDB) DeepCopy() RR {
	return &AFSDB{
		rr.Hdr,
		rr.Subtype,
		rr.Hostname,
	}
}

func (rr *X25) DeepCopy() RR {
	return &X25{
		rr.Hdr,
		rr.PSDNAddress,
	}
}

func (rr *ISDN) DeepCopy() RR {
	return &ISDN{
		rr.Hdr,
		rr.Address,
		rr.SubAddress,
	}
}

func (rr *RT) DeepCopy() RR {
	return &RT{
		rr.Hdr,
		rr.Preference,
		rr.Host,
	}
}

func (rr *NS) DeepCopy() RR {
	return &NS{
		rr.Hdr,
		rr.Ns,
	}
}

func (rr *PTR) DeepCopy() RR {
	return &PTR{
		rr.Hdr,
		rr.Ptr,
	}
}

func (rr *RP) DeepCopy() RR {
	return &RP{
		rr.Hdr,
		rr.Mbox,
		rr.Txt,
	}
}

func (rr *SOA) DeepCopy() RR {
	return &SOA{
		rr.Hdr,
		rr.Ns,
		rr.Mbox,
		rr.Serial,
		rr.Refresh,
		rr.Retry,
		rr.Expire,
		rr.Minttl,
	}
}

func (rr *TXT) DeepCopy() RR {
	return &TXT{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SPF) DeepCopy() RR {
	return &SPF{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *AVC) DeepCopy() RR {
	return &AVC{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SRV) DeepCopy() RR {
	return &SRV{
		rr.Hdr,
		rr.Priority,
		rr.Weight,
		rr.Port,
		rr.Target,
	}
}

func (rr *NAPTR) DeepCopy() RR {
	return &NAPTR{
		rr.Hdr,
		rr.Order,
		rr.Preference,
		rr.Flags,
		rr.Service,
		rr.Regexp,
		rr.Replacement,
	}
}

func (rr *CERT) DeepCopy() RR {
	return &CERT{
		rr.Hdr,
		rr.Type,
		rr.KeyTag,
		rr.Algorithm,
		rr.Certificate,
	}
}

func (rr *DNAME) DeepCopy() RR {
	return &DNAME{
		rr.Hdr,
		rr.Target,
	}
}

func (rr *A) DeepCopy() RR {
	return &A{
		rr.Hdr,
		rr.A,
	}
}

func (rr *AAAA) DeepCopy() RR {
	return &AAAA{
		rr.Hdr,
		rr.AAAA,
	}
}

func (rr *PX) DeepCopy() RR {
	return &PX{
		rr.Hdr,
		rr.Preference,
		rr.Map822,
		rr.Mapx400,
	}
}

func (rr *GPOS) DeepCopy() RR {
	return &GPOS{
		rr.Hdr,
		rr.Longitude,
		rr.Latitude,
		rr.Altitude,
	}
}

func (rr *LOC) DeepCopy() RR {
	return &LOC{
		rr.Hdr,
		rr.Version,
		rr.Size,
		rr.HorizPre,
		rr.VertPre,
		rr.Latitude,
		rr.Longitude,
		rr.Altitude,
	}
}

func (rr *SIG) DeepCopy() RR {
	return &SIG{*rr.RRSIG.DeepCopy().(*RRSIG)}
}
func (rr *RRSIG) DeepCopy() RR {
	return &RRSIG{
		rr.Hdr,
		rr.TypeCovered,
		rr.Algorithm,
		rr.Labels,
		rr.OrigTTL,
		rr.Expiration,
		rr.Inception,
		rr.KeyTag,
		rr.SignerName,
		rr.Signature,
	}
}

func (rr *NXT) DeepCopy() RR {
	return &NXT{*rr.NSEC.DeepCopy().(*NSEC)}
}
func (rr *NSEC) DeepCopy() RR {
	return &NSEC{
		rr.Hdr,
		rr.NextDomain,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *DLV) DeepCopy() RR {
	return &DLV{*rr.DS.DeepCopy().(*DS)}
}
func (rr *CDS) DeepCopy() RR {
	return &CDS{*rr.DS.DeepCopy().(*DS)}
}
func (rr *DS) DeepCopy() RR {
	return &DS{
		rr.Hdr,
		rr.KeyTag,
		rr.Algorithm,
		rr.DigestType,
		rr.Digest,
	}
}

func (rr *KX) DeepCopy() RR {
	return &KX{
		rr.Hdr,
		rr.Preference,
		rr.Exchanger,
	}
}

func (rr *TA) DeepCopy() RR {
	return &TA{
		rr.Hdr,
		rr.KeyTag,
		rr.Algorithm,
		rr.DigestType,
		rr.Digest,
	}
}

func (rr *TALINK) DeepCopy() RR {
	return &TALINK{
		rr.Hdr,
		rr.PreviousName,
		rr.NextName,
	}
}

func (rr *SSHFP) DeepCopy() RR {
	return &SSHFP{
		rr.Hdr,
		rr.Algorithm,
		rr.Type,
		rr.FingerPrint,
	}
}

func (rr *KEY) DeepCopy() RR {
	return &KEY{*rr.DNSKEY.DeepCopy().(*DNSKEY)}
}
func (rr *CDNSKEY) DeepCopy() RR {
	return &CDNSKEY{*rr.DNSKEY.DeepCopy().(*DNSKEY)}
}
func (rr *DNSKEY) DeepCopy() RR {
	return &DNSKEY{
		rr.Hdr,
		rr.Flags,
		rr.Protocol,
		rr.Algorithm,
		rr.PublicKey,
	}
}

func (rr *RKEY) DeepCopy() RR {
	return &RKEY{
		rr.Hdr,
		rr.Flags,
		rr.Protocol,
		rr.Algorithm,
		rr.PublicKey,
	}
}

func (rr *NSAPPTR) DeepCopy() RR {
	return &NSAPPTR{
		rr.Hdr,
		rr.Ptr,
	}
}

func (rr *NSEC3) DeepCopy() RR {
	return &NSEC3{
		rr.Hdr,
		rr.Hash,
		rr.Flags,
		rr.Iterations,
		rr.SaltLength,
		rr.Salt,
		rr.HashLength,
		rr.NextDomain,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *NSEC3PARAM) DeepCopy() RR {
	return &NSEC3PARAM{
		rr.Hdr,
		rr.Hash,
		rr.Flags,
		rr.Iterations,
		rr.SaltLength,
		rr.Salt,
	}
}

func (rr *TKEY) DeepCopy() RR {
	return &TKEY{
		rr.Hdr,
		rr.Algorithm,
		rr.Inception,
		rr.Expiration,
		rr.Mode,
		rr.Error,
		rr.KeySize,
		rr.Key,
		rr.OtherLen,
		rr.OtherData,
	}
}

func (rr *RFC3597) DeepCopy() RR {
	return &RFC3597{
		rr.Hdr,
		rr.Rdata,
	}
}

func (rr *URI) DeepCopy() RR {
	return &URI{
		rr.Hdr,
		rr.Priority,
		rr.Weight,
		rr.Target,
	}
}

func (rr *DHCID) DeepCopy() RR {
	return &DHCID{
		rr.Hdr,
		rr.Digest,
	}
}

func (rr *TLSA) DeepCopy() RR {
	return &TLSA{
		rr.Hdr,
		rr.Usage,
		rr.Selector,
		rr.MatchingType,
		rr.Certificate,
	}
}

func (rr *SMIMEA) DeepCopy() RR {
	return &SMIMEA{
		rr.Hdr,
		rr.Usage,
		rr.Selector,
		rr.MatchingType,
		rr.Certificate,
	}
}

func (rr *HIP) DeepCopy() RR {
	return &HIP{
		rr.Hdr,
		rr.HitLength,
		rr.PublicKeyAlgorithm,
		rr.PublicKeyLength,
		rr.Hit,
		rr.PublicKey,
		slices.Clone(rr.RendezvousServers),
	}
}

func (rr *NINFO) DeepCopy() RR {
	return &NINFO{
		rr.Hdr,
		slices.Clone(rr.ZSData),
	}
}

func (rr *NID) DeepCopy() RR {
	return &NID{
		rr.Hdr,
		rr.Preference,
		rr.NodeID,
	}
}

func (rr *L32) DeepCopy() RR {
	return &L32{
		rr.Hdr,
		rr.Preference,
		rr.Locator32,
	}
}

func (rr *L64) DeepCopy() RR {
	return &L64{
		rr.Hdr,
		rr.Preference,
		rr.Locator64,
	}
}

func (rr *LP) DeepCopy() RR {
	return &LP{
		rr.Hdr,
		rr.Preference,
		rr.Fqdn,
	}
}

func (rr *EUI48) DeepCopy() RR {
	return &EUI48{
		rr.Hdr,
		rr.Address,
	}
}

func (rr *EUI64) DeepCopy() RR {
	return &EUI64{
		rr.Hdr,
		rr.Address,
	}
}

func (rr *CAA) DeepCopy() RR {
	return &CAA{
		rr.Hdr,
		rr.Flag,
		rr.Tag,
		rr.Value,
	}
}

func (rr *UID) DeepCopy() RR {
	return &UID{
		rr.Hdr,
		rr.Uid,
	}
}

func (rr *GID) DeepCopy() RR {
	return &GID{
		rr.Hdr,
		rr.Gid,
	}
}

func (rr *UINFO) DeepCopy() RR {
	return &UINFO{
		rr.Hdr,
		rr.Uinfo,
	}
}

func (rr *EID) DeepCopy() RR {
	return &EID{
		rr.Hdr,
		rr.Endpoint,
	}
}

func (rr *NIMLOC) DeepCopy() RR {
	return &NIMLOC{
		rr.Hdr,
		rr.Locator,
	}
}

func (rr *OPENPGPKEY) DeepCopy() RR {
	return &OPENPGPKEY{
		rr.Hdr,
		rr.PublicKey,
	}
}

func (rr *CSYNC) DeepCopy() RR {
	return &CSYNC{
		rr.Hdr,
		rr.Serial,
		rr.Flags,
		slices.Clone(rr.TypeBitMap),
	}
}

func (rr *ZONEMD) DeepCopy() RR {
	return &ZONEMD{
		rr.Hdr,
		rr.Serial,
		rr.Scheme,
		rr.Hash,
		rr.Digest,
	}
}

func (rr *OPT) DeepCopy() RR {
	return &OPT{
		rr.Hdr,
		slices.Clone(rr.Options),
	}
}

func (rr *RESINFO) DeepCopy() RR {
	return &RESINFO{
		rr.Hdr,
		slices.Clone(rr.Txt),
	}
}

func (rr *SVCB) DeepCopy() RR {
	return &SVCB{
		rr.Hdr,
		rr.Priority,
		rr.Target,
		func() []svcb.Pair {
			pairs := make([]svcb.Pair, len(rr.Value))
			for i, p := range rr.Value {
				pairs[i] = p.DeepCopy()
			}
			return pairs
		}(),
	}
}

func (rr *HTTPS) DeepCopy() RR {
	return &HTTPS{*rr.SVCB.DeepCopy().(*SVCB)}
}
func (rr *DELEG) DeepCopy() RR {
	return &DELEG{
		rr.Hdr,
		func() []deleg.Info {
			infos := make([]deleg.Info, len(rr.Value))
			for i, p := range rr.Value {
				infos[i] = p.DeepCopy()
			}
			return infos
		}(),
	}
}

func (rr *DELEGI) DeepCopy() RR {
	return &DELEGI{*rr.DELEG.DeepCopy().(*DELEG)}
}
func (rr *DSYNC) DeepCopy() RR {
	return &DSYNC{
		rr.Hdr,
		rr.Type,
		rr.Scheme,
		rr.Port,
		rr.Target,
	}
}

func (rr *ANY) DeepCopy() RR {
	return &ANY{
		rr.Hdr,
	}
}

func (rr *AXFR) DeepCopy() RR {
	return &AXFR{
		rr.Hdr,
	}
}

func (rr *IXFR) DeepCopy() RR {
	return &IXFR{
		rr.Hdr,
	}
}

func (rr *TSIG) DeepCopy() RR {
	return &TSIG{
		rr.Hdr,
		rr.Algorithm,
		rr.TimeSigned,
		rr.Fudge,
		rr.MACSize,
		rr.MAC,
		rr.OrigID,
		rr.Error,
		rr.OtherLen,
		rr.OtherData,
	}
}

func (rr *LLQ) DeepCopy() RR {
	return &LLQ{
		rr.Version,
		rr.Opcode,
		rr.Error,
		rr.ID,
		rr.LeaseLife,
	}
}

func (rr *REPORTING) DeepCopy() RR {
	return &REPORTING{
		rr.AgentDomain,
	}
}

func (rr *COOKIE) DeepCopy() RR {
	return &COOKIE{
		rr.Cookie,
	}
}

func (rr *NSID) DeepCopy() RR {
	return &NSID{
		rr.Nsid,
	}
}

func (rr *PADDING) DeepCopy() RR {
	return &PADDING{
		rr.Padding,
	}
}

func (rr *EXPIRE) DeepCopy() RR {
	return &EXPIRE{
		rr.Expire,
	}
}

func (rr *DAU) DeepCopy() RR {
	return &DAU{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *DHU) DeepCopy() RR {
	return &DHU{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *N3U) DeepCopy() RR {
	return &N3U{
		slices.Clone(rr.AlgCode),
	}
}

func (rr *TCPKEEPALIVE) DeepCopy() RR {
	return &TCPKEEPALIVE{
		rr.Timeout,
		rr.Length,
	}
}

func (rr *EDE) DeepCopy() RR {
	return &EDE{
		rr.InfoCode,
		rr.ExtraText,
	}
}

func (rr *SUBNET) DeepCopy() RR {
	return &SUBNET{
		rr.Family,
		rr.SourceNetmask,
		rr.SourceScope,
		rr.Address,
	}
}

func (rr *ESU) DeepCopy() RR {
	return &ESU{
		rr.URI,
	}
}

func (rr *ZONEVERSION) DeepCopy() RR {
	return &ZONEVERSION{
		rr.Labels,
		rr.Type,
		slices.Clone(rr.Version),
	}
}

func (rr *KEEPALIVE) DeepCopy() RR {
	return &KEEPALIVE{
		rr.InactivityTimeout,
		rr.KeepAliveInterval,
	}
}
