// Code generated by "go run ednsrr_generate.go"; DO NOT EDIT.

package dns

func (rr *LLQ) Header() *Header          { return &Header{Name: "."} }
func (rr *LLQ) Pseudo() bool             { return true }
func (rr *REPORTING) Header() *Header    { return &Header{Name: "."} }
func (rr *REPORTING) Pseudo() bool       { return true }
func (rr *COOKIE) Header() *Header       { return &Header{Name: "."} }
func (rr *COOKIE) Pseudo() bool          { return true }
func (rr *NSID) Header() *Header         { return &Header{Name: "."} }
func (rr *NSID) Pseudo() bool            { return true }
func (rr *PADDING) Header() *Header      { return &Header{Name: "."} }
func (rr *PADDING) Pseudo() bool         { return true }
func (rr *EXPIRE) Header() *Header       { return &Header{Name: "."} }
func (rr *EXPIRE) Pseudo() bool          { return true }
func (rr *DAU) Header() *Header          { return &Header{Name: "."} }
func (rr *DAU) Pseudo() bool             { return true }
func (rr *DHU) Header() *Header          { return &Header{Name: "."} }
func (rr *DHU) Pseudo() bool             { return true }
func (rr *N3U) Header() *Header          { return &Header{Name: "."} }
func (rr *N3U) Pseudo() bool             { return true }
func (rr *TCPKEEPALIVE) Header() *Header { return &Header{Name: "."} }
func (rr *TCPKEEPALIVE) Pseudo() bool    { return true }
func (rr *EDE) Header() *Header          { return &Header{Name: "."} }
func (rr *EDE) Pseudo() bool             { return true }
func (rr *SUBNET) Header() *Header       { return &Header{Name: "."} }
func (rr *SUBNET) Pseudo() bool          { return true }
func (rr *ESU) Header() *Header          { return &Header{Name: "."} }
func (rr *ESU) Pseudo() bool             { return true }

// CodeToRR is a map of constructors for each EDNS0 RR type.
var CodeToRR = map[uint16]func() EDNS0{
	CodeLLQ:          func() EDNS0 { return new(LLQ) },
	CodeREPORTING:    func() EDNS0 { return new(REPORTING) },
	CodeCOOKIE:       func() EDNS0 { return new(COOKIE) },
	CodeNSID:         func() EDNS0 { return new(NSID) },
	CodePADDING:      func() EDNS0 { return new(PADDING) },
	CodeEXPIRE:       func() EDNS0 { return new(EXPIRE) },
	CodeDAU:          func() EDNS0 { return new(DAU) },
	CodeDHU:          func() EDNS0 { return new(DHU) },
	CodeN3U:          func() EDNS0 { return new(N3U) },
	CodeTCPKEEPALIVE: func() EDNS0 { return new(TCPKEEPALIVE) },
	CodeEDE:          func() EDNS0 { return new(EDE) },
	CodeSUBNET:       func() EDNS0 { return new(SUBNET) },
	CodeESU:          func() EDNS0 { return new(ESU) },
}

// RRToCode is the reverse of CodeToRR, implemented as a function.
func RRToCode(rr EDNS0) uint16 {
	switch rr.(type) {
	case *LLQ:
		return CodeLLQ
	case *REPORTING:
		return CodeREPORTING
	case *COOKIE:
		return CodeCOOKIE
	case *NSID:
		return CodeNSID
	case *PADDING:
		return CodePADDING
	case *EXPIRE:
		return CodeEXPIRE
	case *DAU:
		return CodeDAU
	case *DHU:
		return CodeDHU
	case *N3U:
		return CodeN3U
	case *TCPKEEPALIVE:
		return CodeTCPKEEPALIVE
	case *EDE:
		return CodeEDE
	case *SUBNET:
		return CodeSUBNET
	case *ESU:
		return CodeESU
	}
	return CodeNone
}

// CodeToString is a map of strings for each EDNS0 RR type.
var CodeToString = map[uint16]string{
	CodeLLQ:          "LLQ",
	CodeREPORTING:    "REPORTING",
	CodeCOOKIE:       "COOKIE",
	CodeNSID:         "NSID",
	CodePADDING:      "PADDING",
	CodeEXPIRE:       "EXPIRE",
	CodeDAU:          "DAU",
	CodeDHU:          "DHU",
	CodeN3U:          "N3U",
	CodeTCPKEEPALIVE: "TCPKEEPALIVE",
	CodeEDE:          "EDE",
	CodeSUBNET:       "SUBNET",
	CodeESU:          "ESU",
}
