// Code generated by "go run len_generate.go"; DO NOT EDIT.

package dns

import (
	"encoding/base64"
	"net"
)

func (rr *NULL) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Null)
	return l
}

func (rr *NXNAME) Len() int {
	l := rr.Hdr.Len()
	return l
}

func (rr *CNAME) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Target) + 1
	return l
}

func (rr *HINFO) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Cpu) + 1
	l += len(rr.Os) + 1
	return l
}

func (rr *MB) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Mb) + 1
	return l
}

func (rr *MG) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Mg) + 1
	return l
}

func (rr *MINFO) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Rmail) + 1
	l += len(rr.Email) + 1
	return l
}

func (rr *MR) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Mr) + 1
	return l
}

func (rr *MF) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Mf) + 1
	return l
}

func (rr *MD) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Md) + 1
	return l
}

func (rr *MX) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Preference
	l += len(rr.Mx) + 1
	return l
}

func (rr *AFSDB) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Subtype
	l += len(rr.Hostname) + 1
	return l
}

func (rr *X25) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.PSDNAddress) + 1
	return l
}

func (rr *ISDN) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Address) + 1
	l += len(rr.SubAddress) + 1
	return l
}

func (rr *RT) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Preference
	l += len(rr.Host) + 1
	return l
}

func (rr *NS) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Ns) + 1
	return l
}

func (rr *PTR) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Ptr) + 1
	return l
}

func (rr *RP) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Mbox) + 1
	l += len(rr.Txt) + 1
	return l
}

func (rr *SOA) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Ns) + 1
	l += len(rr.Mbox) + 1
	l += 4 // Serial
	l += 4 // Refresh
	l += 4 // Retry
	l += 4 // Expire
	l += 4 // Minttl
	return l
}

func (rr *TXT) Len() int {
	l := rr.Hdr.Len()
	for _, x := range rr.Txt {
		l += len(x) + 1
	}
	return l
}

func (rr *SPF) Len() int {
	return rr.TXT.Len()
}
func (rr *AVC) Len() int {
	return rr.TXT.Len()
}
func (rr *WALLET) Len() int {
	return rr.TXT.Len()
}
func (rr *CLA) Len() int {
	return rr.TXT.Len()
}
func (rr *IPN) Len() int {
	l := rr.Hdr.Len()
	l += 8 // Node
	return l
}

func (rr *SRV) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Priority
	l += 2 // Weight
	l += 2 // Port
	l += len(rr.Target) + 1
	return l
}

func (rr *NAPTR) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Order
	l += 2 // Preference
	l += len(rr.Flags) + 1
	l += len(rr.Service) + 1
	l += len(rr.Regexp) + 1
	l += len(rr.Replacement) + 1
	return l
}

func (rr *CERT) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Type
	l += 2 // KeyTag
	l++    // Algorithm
	l += base64.StdEncoding.DecodedLen(len(rr.Certificate))
	return l
}

func (rr *DNAME) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Target) + 1
	return l
}

func (rr *A) Len() int {
	l := rr.Hdr.Len()
	if rr.A.IsValid() {
		l += net.IPv4len
	}
	return l
}

func (rr *AAAA) Len() int {
	l := rr.Hdr.Len()
	if rr.AAAA.IsValid() {
		l += net.IPv6len
	}
	return l
}

func (rr *PX) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Preference
	l += len(rr.Map822) + 1
	l += len(rr.Mapx400) + 1
	return l
}

func (rr *GPOS) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Longitude) + 1
	l += len(rr.Latitude) + 1
	l += len(rr.Altitude) + 1
	return l
}

func (rr *LOC) Len() int {
	l := rr.Hdr.Len()
	l++    // Version
	l++    // Size
	l++    // HorizPre
	l++    // VertPre
	l += 4 // Latitude
	l += 4 // Longitude
	l += 4 // Altitude
	return l
}

func (rr *SIG) Len() int {
	return rr.RRSIG.Len()
}
func (rr *RRSIG) Len() int {
	l := rr.Hdr.Len()
	l += 2 // TypeCovered
	l++    // Algorithm
	l++    // Labels
	l += 4 // OrigTTL
	l += 4 // Expiration
	l += 4 // Inception
	l += 2 // KeyTag
	l += len(rr.SignerName) + 1
	l += base64.StdEncoding.DecodedLen(len(rr.Signature))
	return l
}

func (rr *NXT) Len() int {
	return rr.NSEC.Len()
}
func (rr *DLV) Len() int {
	return rr.DS.Len()
}
func (rr *CDS) Len() int {
	return rr.DS.Len()
}
func (rr *DS) Len() int {
	l := rr.Hdr.Len()
	l += 2 // KeyTag
	l++    // Algorithm
	l++    // DigestType
	l += len(rr.Digest) / 2
	return l
}

func (rr *KX) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Preference
	l += len(rr.Exchanger) + 1
	return l
}

func (rr *TA) Len() int {
	l := rr.Hdr.Len()
	l += 2 // KeyTag
	l++    // Algorithm
	l++    // DigestType
	l += len(rr.Digest) / 2
	return l
}

func (rr *TALINK) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.PreviousName) + 1
	l += len(rr.NextName) + 1
	return l
}

func (rr *SSHFP) Len() int {
	l := rr.Hdr.Len()
	l++ // Algorithm
	l++ // Type
	l += len(rr.FingerPrint) / 2
	return l
}

func (rr *KEY) Len() int {
	return rr.DNSKEY.Len()
}
func (rr *CDNSKEY) Len() int {
	return rr.DNSKEY.Len()
}
func (rr *DNSKEY) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Flags
	l++    // Protocol
	l++    // Algorithm
	l += base64.StdEncoding.DecodedLen(len(rr.PublicKey))
	return l
}

func (rr *RKEY) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Flags
	l++    // Protocol
	l++    // Algorithm
	l += base64.StdEncoding.DecodedLen(len(rr.PublicKey))
	return l
}

func (rr *NSAPPTR) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Ptr) + 1
	return l
}

func (rr *NSEC3PARAM) Len() int {
	l := rr.Hdr.Len()
	l++    // Hash
	l++    // Flags
	l += 2 // Iterations
	l++    // SaltLength
	l += len(rr.Salt) / 2
	return l
}

func (rr *TKEY) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Algorithm) + 1
	l += 4 // Inception
	l += 4 // Expiration
	l += 2 // Mode
	l += 2 // Error
	l += 2 // KeySize
	l += len(rr.Key) / 2
	l += 2 // OtherLen
	l += len(rr.OtherData) / 2
	return l
}

func (rr *RFC3597) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Data) / 2
	return l
}

func (rr *URI) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Priority
	l += 2 // Weight
	l += len(rr.Target)
	return l
}

func (rr *DHCID) Len() int {
	l := rr.Hdr.Len()
	l += base64.StdEncoding.DecodedLen(len(rr.Digest))
	return l
}

func (rr *TLSA) Len() int {
	l := rr.Hdr.Len()
	l++ // Usage
	l++ // Selector
	l++ // MatchingType
	l += len(rr.Certificate) / 2
	return l
}

func (rr *SMIMEA) Len() int {
	l := rr.Hdr.Len()
	l++ // Usage
	l++ // Selector
	l++ // MatchingType
	l += len(rr.Certificate) / 2
	return l
}

func (rr *HIP) Len() int {
	l := rr.Hdr.Len()
	l++    // HitLength
	l++    // PublicKeyAlgorithm
	l += 2 // PublicKeyLength
	l += len(rr.Hit) / 2
	l += base64.StdEncoding.DecodedLen(len(rr.PublicKey))
	for _, x := range rr.RendezvousServers {
		l += len(x) + 1
	}
	return l
}

func (rr *NINFO) Len() int {
	l := rr.Hdr.Len()
	for _, x := range rr.ZSData {
		l += len(x) + 1
	}
	return l
}

func (rr *NID) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Preference
	l += 8 // NodeID
	return l
}

func (rr *L32) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Preference
	if rr.Locator32.IsValid() {
		l += net.IPv4len
	}
	return l
}

func (rr *L64) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Preference
	l += 8 // Locator64
	return l
}

func (rr *LP) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Preference
	l += len(rr.Fqdn) + 1
	return l
}

func (rr *EUI48) Len() int {
	l := rr.Hdr.Len()
	l += 6 // Address
	return l
}

func (rr *EUI64) Len() int {
	l := rr.Hdr.Len()
	l += 8 // Address
	return l
}

func (rr *CAA) Len() int {
	l := rr.Hdr.Len()
	l++ // Flag
	l += len(rr.Tag) + 1
	l += len(rr.Value)
	return l
}

func (rr *UID) Len() int {
	l := rr.Hdr.Len()
	l += 4 // Uid
	return l
}

func (rr *GID) Len() int {
	l := rr.Hdr.Len()
	l += 4 // Gid
	return l
}

func (rr *UINFO) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Uinfo) + 1
	return l
}

func (rr *EID) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Endpoint) / 2
	return l
}

func (rr *NIMLOC) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Locator) / 2
	return l
}

func (rr *OPENPGPKEY) Len() int {
	l := rr.Hdr.Len()
	l += base64.StdEncoding.DecodedLen(len(rr.PublicKey))
	return l
}

func (rr *ZONEMD) Len() int {
	l := rr.Hdr.Len()
	l += 4 // Serial
	l++    // Scheme
	l++    // Hash
	l += len(rr.Digest) / 2
	return l
}

func (rr *RESINFO) Len() int {
	l := rr.Hdr.Len()
	for _, x := range rr.Txt {
		l += len(x) + 1
	}
	return l
}

func (rr *SVCB) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Priority
	l += len(rr.Target) + 1
	for _, x := range rr.Value {
		l += x.Len()
	}
	return l
}

func (rr *HTTPS) Len() int {
	return rr.SVCB.Len()
}
func (rr *DELEG) Len() int {
	l := rr.Hdr.Len()
	for _, x := range rr.Value {
		l += x.Len()
	}
	return l
}

func (rr *DELEGI) Len() int {
	return rr.DELEG.Len()
}
func (rr *DSYNC) Len() int {
	l := rr.Hdr.Len()
	l += 2 // Type
	l++    // Scheme
	l += 2 // Port
	l += len(rr.Target) + 1
	return l
}

func (rr *ANY) Len() int {
	l := rr.Hdr.Len()
	return l
}

func (rr *AXFR) Len() int {
	l := rr.Hdr.Len()
	return l
}

func (rr *IXFR) Len() int {
	l := rr.Hdr.Len()
	return l
}

func (rr *TSIG) Len() int {
	l := rr.Hdr.Len()
	l += len(rr.Algorithm) + 1
	l += 6 // TimeSigned
	l += 2 // Fudge
	l += 2 // MACSize
	l += len(rr.MAC) / 2
	l += 2 // OrigID
	l += 2 // Error
	l += 2 // OtherLen
	l += len(rr.OtherData) / 2
	return l
}
