// Code generated by "go run msg_generate.go"; DO NOT EDIT.

package dns

import (
	"codeberg.org/miekg/dns/internal/pack"
	"codeberg.org/miekg/dns/internal/unpack"
	"golang.org/x/crypto/cryptobyte"
)

func (rr *NULL) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.StringAny(rr.Null, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NULL) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Null, err = unpack.StringAny(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NULL")
	}
	return nil
}

func (rr *NXNAME) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *NXNAME) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NXNAME")
	}
	return nil
}

func (rr *CNAME) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Target, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *CNAME) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Target, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "CNAME")
	}
	return nil
}

func (rr *HINFO) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.String(rr.Cpu, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.String(rr.Os, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *HINFO) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Cpu, err = unpack.String(&s)
	if err != nil {
		return err
	}
	rr.Os, err = unpack.String(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "HINFO")
	}
	return nil
}

func (rr *MB) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Mb, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *MB) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Mb, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "MB")
	}
	return nil
}

func (rr *MG) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Mg, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *MG) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Mg, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "MG")
	}
	return nil
}

func (rr *MINFO) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Rmail, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Email, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *MINFO) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Rmail, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	rr.Email, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "MINFO")
	}
	return nil
}

func (rr *MR) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Mr, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *MR) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Mr, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "MR")
	}
	return nil
}

func (rr *MF) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Mf, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *MF) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Mf, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "MF")
	}
	return nil
}

func (rr *MD) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Md, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *MD) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Md, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "MD")
	}
	return nil
}

func (rr *MX) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Mx, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *MX) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	rr.Mx, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "MX")
	}
	return nil
}

func (rr *AFSDB) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Subtype, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Hostname, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *AFSDB) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Subtype) {
		return ErrUnpackOverflow
	}
	rr.Hostname, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "AFSDB")
	}
	return nil
}

func (rr *X25) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.String(rr.PSDNAddress, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *X25) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.PSDNAddress, err = unpack.String(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "X25")
	}
	return nil
}

func (rr *ISDN) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.String(rr.Address, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.String(rr.SubAddress, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *ISDN) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Address, err = unpack.String(&s)
	if err != nil {
		return err
	}
	rr.SubAddress, err = unpack.String(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "ISDN")
	}
	return nil
}

func (rr *RT) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Host, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *RT) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	rr.Host, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "RT")
	}
	return nil
}

func (rr *NS) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Ns, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NS) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Ns, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NS")
	}
	return nil
}

func (rr *PTR) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Ptr, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *PTR) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Ptr, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "PTR")
	}
	return nil
}

func (rr *RP) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Mbox, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Txt, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *RP) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Mbox, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	rr.Txt, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "RP")
	}
	return nil
}

func (rr *SOA) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Ns, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Mbox, msg, off, compression, true)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Serial, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Refresh, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Retry, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Expire, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Minttl, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *SOA) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Ns, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	rr.Mbox, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.ReadUint32(&rr.Serial) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Refresh) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Retry) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Expire) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Minttl) {
		return ErrUnpackOverflow
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "SOA")
	}
	return nil
}

func (rr *TXT) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringTxt(rr.Txt, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *TXT) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Txt, err = unpackStringTxt(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "TXT")
	}
	return nil
}

func (rr *SPF) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringTxt(rr.Txt, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *SPF) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Txt, err = unpackStringTxt(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "SPF")
	}
	return nil
}

func (rr *AVC) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringTxt(rr.Txt, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *AVC) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Txt, err = unpackStringTxt(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "AVC")
	}
	return nil
}

func (rr *SRV) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Priority, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Weight, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Port, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Target, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *SRV) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Priority) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Weight) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Port) {
		return ErrUnpackOverflow
	}
	rr.Target, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "SRV")
	}
	return nil
}

func (rr *NAPTR) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Order, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.String(rr.Flags, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.String(rr.Service, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.String(rr.Regexp, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Replacement, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NAPTR) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Order) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	rr.Flags, err = unpack.String(&s)
	if err != nil {
		return err
	}
	rr.Service, err = unpack.String(&s)
	if err != nil {
		return err
	}
	rr.Regexp, err = unpack.String(&s)
	if err != nil {
		return err
	}
	rr.Replacement, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NAPTR")
	}
	return nil
}

func (rr *CERT) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Type, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.KeyTag, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Algorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringBase64(rr.Certificate, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *CERT) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Type) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.KeyTag) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Algorithm) {
		return ErrUnpackOverflow
	}
	rr.Certificate, err = unpackStringBase64(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "CERT")
	}
	return nil
}

func (rr *DNAME) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Target, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *DNAME) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Target, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "DNAME")
	}
	return nil
}

func (rr *A) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.A(rr.A, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *A) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.A, err = unpack.A(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "A")
	}
	return nil
}

func (rr *AAAA) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.AAAA(rr.AAAA, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *AAAA) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.AAAA, err = unpack.AAAA(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "AAAA")
	}
	return nil
}

func (rr *PX) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Map822, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Mapx400, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *PX) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	rr.Map822, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	rr.Mapx400, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "PX")
	}
	return nil
}

func (rr *GPOS) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.String(rr.Longitude, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.String(rr.Latitude, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.String(rr.Altitude, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *GPOS) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Longitude, err = unpack.String(&s)
	if err != nil {
		return err
	}
	rr.Latitude, err = unpack.String(&s)
	if err != nil {
		return err
	}
	rr.Altitude, err = unpack.String(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "GPOS")
	}
	return nil
}

func (rr *LOC) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Version, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Size, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.HorizPre, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.VertPre, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Latitude, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Longitude, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Altitude, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *LOC) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Version) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Size) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.HorizPre) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.VertPre) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Latitude) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Longitude) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Altitude) {
		return ErrUnpackOverflow
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "LOC")
	}
	return nil
}

func (rr *SIG) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *SIG) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "SIG")
	}
	return nil
}

func (rr *RRSIG) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.TypeCovered, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Algorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Labels, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.OrigTTL, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Expiration, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Inception, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.KeyTag, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.SignerName, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	off, err = packStringBase64(rr.Signature, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *RRSIG) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.TypeCovered) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Algorithm) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Labels) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.OrigTTL) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Expiration) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Inception) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.KeyTag) {
		return ErrUnpackOverflow
	}
	rr.SignerName, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	rr.Signature, err = unpackStringBase64(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "RRSIG")
	}
	return nil
}

func (rr *NXT) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *NXT) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NXT")
	}
	return nil
}

func (rr *NSEC) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.NextDomain, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	off, err = packNsec(rr.TypeBitMap, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NSEC) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.NextDomain, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	rr.TypeBitMap, err = unpackNsec(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NSEC")
	}
	return nil
}

func (rr *DLV) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *DLV) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "DLV")
	}
	return nil
}

func (rr *CDS) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *CDS) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "CDS")
	}
	return nil
}

func (rr *DS) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.KeyTag, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Algorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.DigestType, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.Digest, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *DS) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.KeyTag) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Algorithm) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.DigestType) {
		return ErrUnpackOverflow
	}
	rr.Digest, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "DS")
	}
	return nil
}

func (rr *KX) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Exchanger, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *KX) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	rr.Exchanger, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "KX")
	}
	return nil
}

func (rr *TA) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.KeyTag, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Algorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.DigestType, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.Digest, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *TA) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.KeyTag) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Algorithm) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.DigestType) {
		return ErrUnpackOverflow
	}
	rr.Digest, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "TA")
	}
	return nil
}

func (rr *TALINK) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.PreviousName, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.NextName, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *TALINK) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.PreviousName, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	rr.NextName, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "TALINK")
	}
	return nil
}

func (rr *SSHFP) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Algorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Type, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.FingerPrint, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *SSHFP) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Algorithm) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Type) {
		return ErrUnpackOverflow
	}
	rr.FingerPrint, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "SSHFP")
	}
	return nil
}

func (rr *KEY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *KEY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "KEY")
	}
	return nil
}

func (rr *CDNSKEY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *CDNSKEY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "CDNSKEY")
	}
	return nil
}

func (rr *DNSKEY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Flags, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Protocol, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Algorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringBase64(rr.PublicKey, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *DNSKEY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Flags) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Protocol) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Algorithm) {
		return ErrUnpackOverflow
	}
	rr.PublicKey, err = unpackStringBase64(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "DNSKEY")
	}
	return nil
}

func (rr *IPSECKEY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Precedence, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.GatewayType, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Algorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packIPSECGateway(rr.GatewayAddr, rr.GatewayHost, msg, off, rr.GatewayType, compression, false)
	if err != nil {
		return off, err
	}
	off, err = packStringBase64(rr.PublicKey, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *IPSECKEY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Precedence) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.GatewayType) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Algorithm) {
		return ErrUnpackOverflow
	}
	rr.GatewayAddr, rr.GatewayHost, err = unpackIPSECGateway(&s, msgBuf, rr.GatewayType)
	if err != nil {
		return err
	}
	rr.PublicKey, err = unpackStringBase64(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "IPSECKEY")
	}
	return nil
}

func (rr *AMTRELAY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Precedence, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.GatewayType, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packIPSECGateway(rr.GatewayAddr, rr.GatewayHost, msg, off, rr.GatewayType, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *AMTRELAY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Precedence) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.GatewayType) {
		return ErrUnpackOverflow
	}
	rr.GatewayAddr, rr.GatewayHost, err = unpackIPSECGateway(&s, msgBuf, rr.GatewayType)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "AMTRELAY")
	}
	return nil
}

func (rr *RKEY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Flags, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Protocol, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Algorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringBase64(rr.PublicKey, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *RKEY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Flags) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Protocol) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Algorithm) {
		return ErrUnpackOverflow
	}
	rr.PublicKey, err = unpackStringBase64(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "RKEY")
	}
	return nil
}

func (rr *NSAPPTR) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Ptr, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NSAPPTR) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Ptr, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NSAPPTR")
	}
	return nil
}

func (rr *NSEC3) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Hash, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Flags, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Iterations, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.SaltLength, msg, off)
	if err != nil {
		return off, err
	}
	// Only pack salt if value is not "-", i.e. empty
	if rr.Salt != "-" {
		off, err = packStringHex(rr.Salt, msg, off)
		if err != nil {
			return off, err
		}
	}
	off, err = pack.Uint8(rr.HashLength, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringBase32(rr.NextDomain, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packNsec(rr.TypeBitMap, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NSEC3) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Hash) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Flags) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Iterations) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.SaltLength) {
		return ErrUnpackOverflow
	}
	rr.Salt, err = unpackStringHex(&s, int(rr.SaltLength))
	if err != nil {
		return err
	}
	if !s.ReadUint8(&rr.HashLength) {
		return ErrUnpackOverflow
	}
	rr.NextDomain, err = unpackStringBase32(&s, int(rr.HashLength))
	if err != nil {
		return err
	}
	rr.TypeBitMap, err = unpackNsec(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NSEC3")
	}
	return nil
}

func (rr *NSEC3PARAM) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Hash, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Flags, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Iterations, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.SaltLength, msg, off)
	if err != nil {
		return off, err
	}
	// Only pack salt if value is not "-", i.e. empty
	if rr.Salt != "-" {
		off, err = packStringHex(rr.Salt, msg, off)
		if err != nil {
			return off, err
		}
	}
	return off, nil
}

func (rr *NSEC3PARAM) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Hash) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Flags) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Iterations) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.SaltLength) {
		return ErrUnpackOverflow
	}
	rr.Salt, err = unpackStringHex(&s, int(rr.SaltLength))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NSEC3PARAM")
	}
	return nil
}

func (rr *TKEY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Algorithm, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Inception, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint32(rr.Expiration, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Mode, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Error, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.KeySize, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.Key, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.OtherLen, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.OtherData, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *TKEY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Algorithm, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.ReadUint32(&rr.Inception) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint32(&rr.Expiration) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Mode) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Error) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.KeySize) {
		return ErrUnpackOverflow
	}
	rr.Key, err = unpackStringHex(&s, int(rr.KeySize))
	if err != nil {
		return err
	}
	if !s.ReadUint16(&rr.OtherLen) {
		return ErrUnpackOverflow
	}
	rr.OtherData, err = unpackStringHex(&s, int(rr.OtherLen))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "TKEY")
	}
	return nil
}

func (rr *RFC3597) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringHex(rr.Rdata, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *RFC3597) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Rdata, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "RFC3597")
	}
	return nil
}

func (rr *URI) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Priority, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Weight, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringOctet(rr.Target, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *URI) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Priority) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Weight) {
		return ErrUnpackOverflow
	}
	rr.Target, err = unpackStringOctet(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "URI")
	}
	return nil
}

func (rr *DHCID) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringBase64(rr.Digest, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *DHCID) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Digest, err = unpackStringBase64(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "DHCID")
	}
	return nil
}

func (rr *TLSA) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Usage, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Selector, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.MatchingType, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.Certificate, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *TLSA) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Usage) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Selector) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.MatchingType) {
		return ErrUnpackOverflow
	}
	rr.Certificate, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "TLSA")
	}
	return nil
}

func (rr *SMIMEA) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Usage, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Selector, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.MatchingType, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.Certificate, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *SMIMEA) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Usage) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Selector) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.MatchingType) {
		return ErrUnpackOverflow
	}
	rr.Certificate, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "SMIMEA")
	}
	return nil
}

func (rr *HIP) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.HitLength, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.PublicKeyAlgorithm, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.PublicKeyLength, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.Hit, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringBase64(rr.PublicKey, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packNames(rr.RendezvousServers, msg, off, compression)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *HIP) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.HitLength) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.PublicKeyAlgorithm) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.PublicKeyLength) {
		return ErrUnpackOverflow
	}
	rr.Hit, err = unpackStringHex(&s, int(rr.HitLength))
	if err != nil {
		return err
	}
	rr.PublicKey, err = unpackStringBase64(&s, int(rr.PublicKeyLength))
	if err != nil {
		return err
	}
	rr.RendezvousServers, err = unpackNames(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "HIP")
	}
	return nil
}

func (rr *NINFO) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringTxt(rr.ZSData, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NINFO) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.ZSData, err = unpackStringTxt(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NINFO")
	}
	return nil
}

func (rr *NID) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint64(rr.NodeID, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NID) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint64(&rr.NodeID) {
		return ErrUnpackOverflow
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NID")
	}
	return nil
}

func (rr *L32) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.A(rr.Locator32, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *L32) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	rr.Locator32, err = unpack.A(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "L32")
	}
	return nil
}

func (rr *L64) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint64(rr.Locator64, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *L64) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint64(&rr.Locator64) {
		return ErrUnpackOverflow
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "L64")
	}
	return nil
}

func (rr *LP) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Preference, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Fqdn, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *LP) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Preference) {
		return ErrUnpackOverflow
	}
	rr.Fqdn, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "LP")
	}
	return nil
}

func (rr *EUI48) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint48(rr.Address, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *EUI48) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint48(&rr.Address) {
		return ErrUnpackOverflow
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "EUI48")
	}
	return nil
}

func (rr *EUI64) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint64(rr.Address, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *EUI64) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint64(&rr.Address) {
		return ErrUnpackOverflow
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "EUI64")
	}
	return nil
}

func (rr *CAA) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint8(rr.Flag, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.String(rr.Tag, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringOctet(rr.Value, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *CAA) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint8(&rr.Flag) {
		return ErrUnpackOverflow
	}
	rr.Tag, err = unpack.String(&s)
	if err != nil {
		return err
	}
	rr.Value, err = unpackStringOctet(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "CAA")
	}
	return nil
}

func (rr *UID) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint32(rr.Uid, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *UID) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint32(&rr.Uid) {
		return ErrUnpackOverflow
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "UID")
	}
	return nil
}

func (rr *GID) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint32(rr.Gid, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *GID) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint32(&rr.Gid) {
		return ErrUnpackOverflow
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "GID")
	}
	return nil
}

func (rr *UINFO) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.String(rr.Uinfo, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *UINFO) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Uinfo, err = unpack.String(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "UINFO")
	}
	return nil
}

func (rr *EID) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringHex(rr.Endpoint, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *EID) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Endpoint, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "EID")
	}
	return nil
}

func (rr *NIMLOC) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringHex(rr.Locator, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *NIMLOC) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Locator, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "NIMLOC")
	}
	return nil
}

func (rr *OPENPGPKEY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringBase64(rr.PublicKey, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *OPENPGPKEY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.PublicKey, err = unpackStringBase64(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "OPENPGPKEY")
	}
	return nil
}

func (rr *CSYNC) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint32(rr.Serial, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Flags, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packNsec(rr.TypeBitMap, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *CSYNC) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint32(&rr.Serial) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Flags) {
		return ErrUnpackOverflow
	}
	rr.TypeBitMap, err = unpackNsec(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "CSYNC")
	}
	return nil
}

func (rr *ZONEMD) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint32(rr.Serial, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Scheme, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint8(rr.Hash, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.Digest, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *ZONEMD) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint32(&rr.Serial) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Scheme) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint8(&rr.Hash) {
		return ErrUnpackOverflow
	}
	rr.Digest, err = unpackStringHex(&s, len(s))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "ZONEMD")
	}
	return nil
}

func (rr *OPT) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packOpt(rr.Options, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *OPT) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Options, err = unpackOpt(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "OPT")
	}
	return nil
}

func (rr *RESINFO) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packStringTxt(rr.Txt, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *RESINFO) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Txt, err = unpackStringTxt(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "RESINFO")
	}
	return nil
}

func (rr *APL) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packApl(rr.Prefixes, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *APL) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Prefixes, err = unpackApl(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "APL")
	}
	return nil
}

func (rr *SVCB) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = pack.Uint16(rr.Priority, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packName(rr.Target, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	off, err = packSVCB(rr.Value, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *SVCB) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.ReadUint16(&rr.Priority) {
		return ErrUnpackOverflow
	}
	rr.Target, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	rr.Value, err = unpackSVCB(&s)
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "SVCB")
	}
	return nil
}

func (rr *HTTPS) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *HTTPS) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "HTTPS")
	}
	return nil
}

func (rr *ANY) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *ANY) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "ANY")
	}
	return nil
}

func (rr *AXFR) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *AXFR) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "AXFR")
	}
	return nil
}

func (rr *IXFR) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	return off, nil
}

func (rr *IXFR) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "IXFR")
	}
	return nil
}

func (rr *TSIG) pack(msg []byte, off int, compression map[string]uint16) (off1 int, err error) {
	off, err = packName(rr.Algorithm, msg, off, compression, false)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint48(rr.TimeSigned, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Fudge, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.MACSize, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.MAC, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.OrigID, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.Error, msg, off)
	if err != nil {
		return off, err
	}
	off, err = pack.Uint16(rr.OtherLen, msg, off)
	if err != nil {
		return off, err
	}
	off, err = packStringHex(rr.OtherData, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *TSIG) unpack(data, msgBuf []byte) (err error) {
	s := cryptobyte.String(data)
	rr.Algorithm, err = unpackName(&s, msgBuf)
	if err != nil {
		return err
	}
	if !s.ReadUint48(&rr.TimeSigned) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Fudge) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.MACSize) {
		return ErrUnpackOverflow
	}
	rr.MAC, err = unpackStringHex(&s, int(rr.MACSize))
	if err != nil {
		return err
	}
	if !s.ReadUint16(&rr.OrigID) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.Error) {
		return ErrUnpackOverflow
	}
	if !s.ReadUint16(&rr.OtherLen) {
		return ErrUnpackOverflow
	}
	rr.OtherData, err = unpackStringHex(&s, int(rr.OtherLen))
	if err != nil {
		return err
	}
	if !s.Empty() {
		return ErrTrailingData.Fmt(": %s", "TSIG")
	}
	return nil
}
