// Code generated by "go run rdata_generate.go"; DO NOT EDIT.

package dns

import "codeberg.org/miekg/dns/rdata"
import "io"

// TypeToRDATA is a map of functions for each RR type to set it's rdata.
var TypeToRDATA = map[uint16]func(RR, RDATA){
	TypeNULL:       func(rr RR, rd RDATA) { rr.(*NULL).NULL = rd.(rdata.NULL) },
	TypeNXNAME:     func(rr RR, rd RDATA) {},
	TypeCNAME:      func(rr RR, rd RDATA) { rr.(*CNAME).CNAME = rd.(rdata.CNAME) },
	TypeHINFO:      func(rr RR, rd RDATA) { rr.(*HINFO).HINFO = rd.(rdata.HINFO) },
	TypeMB:         func(rr RR, rd RDATA) { rr.(*MB).MB = rd.(rdata.MB) },
	TypeMG:         func(rr RR, rd RDATA) { rr.(*MG).MG = rd.(rdata.MG) },
	TypeMINFO:      func(rr RR, rd RDATA) { rr.(*MINFO).MINFO = rd.(rdata.MINFO) },
	TypeMR:         func(rr RR, rd RDATA) { rr.(*MR).MR = rd.(rdata.MR) },
	TypeMF:         func(rr RR, rd RDATA) { rr.(*MF).MF = rd.(rdata.MF) },
	TypeMD:         func(rr RR, rd RDATA) { rr.(*MD).MD = rd.(rdata.MD) },
	TypeMX:         func(rr RR, rd RDATA) { rr.(*MX).MX = rd.(rdata.MX) },
	TypeAFSDB:      func(rr RR, rd RDATA) { rr.(*AFSDB).AFSDB = rd.(rdata.AFSDB) },
	TypeX25:        func(rr RR, rd RDATA) { rr.(*X25).X25 = rd.(rdata.X25) },
	TypeISDN:       func(rr RR, rd RDATA) { rr.(*ISDN).ISDN = rd.(rdata.ISDN) },
	TypeRT:         func(rr RR, rd RDATA) { rr.(*RT).RT = rd.(rdata.RT) },
	TypeNS:         func(rr RR, rd RDATA) { rr.(*NS).NS = rd.(rdata.NS) },
	TypePTR:        func(rr RR, rd RDATA) { rr.(*PTR).PTR = rd.(rdata.PTR) },
	TypeRP:         func(rr RR, rd RDATA) { rr.(*RP).RP = rd.(rdata.RP) },
	TypeSOA:        func(rr RR, rd RDATA) { rr.(*SOA).SOA = rd.(rdata.SOA) },
	TypeTXT:        func(rr RR, rd RDATA) { rr.(*TXT).TXT = rd.(rdata.TXT) },
	TypeSPF:        func(rr RR, rd RDATA) { rr.(*SPF).TXT.TXT = rd.(rdata.TXT) },
	TypeAVC:        func(rr RR, rd RDATA) { rr.(*AVC).TXT.TXT = rd.(rdata.TXT) },
	TypeWALLET:     func(rr RR, rd RDATA) { rr.(*WALLET).TXT.TXT = rd.(rdata.TXT) },
	TypeCLA:        func(rr RR, rd RDATA) { rr.(*CLA).TXT.TXT = rd.(rdata.TXT) },
	TypeIPN:        func(rr RR, rd RDATA) { rr.(*IPN).IPN = rd.(rdata.IPN) },
	TypeSRV:        func(rr RR, rd RDATA) { rr.(*SRV).SRV = rd.(rdata.SRV) },
	TypeNAPTR:      func(rr RR, rd RDATA) { rr.(*NAPTR).NAPTR = rd.(rdata.NAPTR) },
	TypeCERT:       func(rr RR, rd RDATA) { rr.(*CERT).CERT = rd.(rdata.CERT) },
	TypeDNAME:      func(rr RR, rd RDATA) { rr.(*DNAME).DNAME = rd.(rdata.DNAME) },
	TypeA:          func(rr RR, rd RDATA) { rr.(*A).A = rd.(rdata.A) },
	TypeAAAA:       func(rr RR, rd RDATA) { rr.(*AAAA).AAAA = rd.(rdata.AAAA) },
	TypePX:         func(rr RR, rd RDATA) { rr.(*PX).PX = rd.(rdata.PX) },
	TypeGPOS:       func(rr RR, rd RDATA) { rr.(*GPOS).GPOS = rd.(rdata.GPOS) },
	TypeLOC:        func(rr RR, rd RDATA) { rr.(*LOC).LOC = rd.(rdata.LOC) },
	TypeSIG:        func(rr RR, rd RDATA) { rr.(*SIG).RRSIG.RRSIG = rd.(rdata.RRSIG) },
	TypeRRSIG:      func(rr RR, rd RDATA) { rr.(*RRSIG).RRSIG = rd.(rdata.RRSIG) },
	TypeNXT:        func(rr RR, rd RDATA) { rr.(*NXT).NSEC.NSEC = rd.(rdata.NSEC) },
	TypeNSEC:       func(rr RR, rd RDATA) { rr.(*NSEC).NSEC = rd.(rdata.NSEC) },
	TypeDLV:        func(rr RR, rd RDATA) { rr.(*DLV).DS.DS = rd.(rdata.DS) },
	TypeCDS:        func(rr RR, rd RDATA) { rr.(*CDS).DS.DS = rd.(rdata.DS) },
	TypeDS:         func(rr RR, rd RDATA) { rr.(*DS).DS = rd.(rdata.DS) },
	TypeKX:         func(rr RR, rd RDATA) { rr.(*KX).KX = rd.(rdata.KX) },
	TypeTA:         func(rr RR, rd RDATA) { rr.(*TA).TA = rd.(rdata.TA) },
	TypeTALINK:     func(rr RR, rd RDATA) { rr.(*TALINK).TALINK = rd.(rdata.TALINK) },
	TypeSSHFP:      func(rr RR, rd RDATA) { rr.(*SSHFP).SSHFP = rd.(rdata.SSHFP) },
	TypeKEY:        func(rr RR, rd RDATA) { rr.(*KEY).DNSKEY.DNSKEY = rd.(rdata.DNSKEY) },
	TypeCDNSKEY:    func(rr RR, rd RDATA) { rr.(*CDNSKEY).DNSKEY.DNSKEY = rd.(rdata.DNSKEY) },
	TypeDNSKEY:     func(rr RR, rd RDATA) { rr.(*DNSKEY).DNSKEY = rd.(rdata.DNSKEY) },
	TypeRKEY:       func(rr RR, rd RDATA) { rr.(*RKEY).RKEY = rd.(rdata.RKEY) },
	TypeNSAPPTR:    func(rr RR, rd RDATA) { rr.(*NSAPPTR).NSAPPTR = rd.(rdata.NSAPPTR) },
	TypeNSEC3:      func(rr RR, rd RDATA) { rr.(*NSEC3).NSEC3 = rd.(rdata.NSEC3) },
	TypeNSEC3PARAM: func(rr RR, rd RDATA) { rr.(*NSEC3PARAM).NSEC3PARAM = rd.(rdata.NSEC3PARAM) },
	TypeTKEY:       func(rr RR, rd RDATA) { rr.(*TKEY).TKEY = rd.(rdata.TKEY) },
	TypeURI:        func(rr RR, rd RDATA) { rr.(*URI).URI = rd.(rdata.URI) },
	TypeDHCID:      func(rr RR, rd RDATA) { rr.(*DHCID).DHCID = rd.(rdata.DHCID) },
	TypeTLSA:       func(rr RR, rd RDATA) { rr.(*TLSA).TLSA = rd.(rdata.TLSA) },
	TypeSMIMEA:     func(rr RR, rd RDATA) { rr.(*SMIMEA).SMIMEA = rd.(rdata.SMIMEA) },
	TypeHIP:        func(rr RR, rd RDATA) { rr.(*HIP).HIP = rd.(rdata.HIP) },
	TypeNINFO:      func(rr RR, rd RDATA) { rr.(*NINFO).NINFO = rd.(rdata.NINFO) },
	TypeNID:        func(rr RR, rd RDATA) { rr.(*NID).NID = rd.(rdata.NID) },
	TypeL32:        func(rr RR, rd RDATA) { rr.(*L32).L32 = rd.(rdata.L32) },
	TypeL64:        func(rr RR, rd RDATA) { rr.(*L64).L64 = rd.(rdata.L64) },
	TypeLP:         func(rr RR, rd RDATA) { rr.(*LP).LP = rd.(rdata.LP) },
	TypeEUI48:      func(rr RR, rd RDATA) { rr.(*EUI48).EUI48 = rd.(rdata.EUI48) },
	TypeEUI64:      func(rr RR, rd RDATA) { rr.(*EUI64).EUI64 = rd.(rdata.EUI64) },
	TypeCAA:        func(rr RR, rd RDATA) { rr.(*CAA).CAA = rd.(rdata.CAA) },
	TypeUID:        func(rr RR, rd RDATA) { rr.(*UID).UID = rd.(rdata.UID) },
	TypeGID:        func(rr RR, rd RDATA) { rr.(*GID).GID = rd.(rdata.GID) },
	TypeUINFO:      func(rr RR, rd RDATA) { rr.(*UINFO).UINFO = rd.(rdata.UINFO) },
	TypeEID:        func(rr RR, rd RDATA) { rr.(*EID).EID = rd.(rdata.EID) },
	TypeNIMLOC:     func(rr RR, rd RDATA) { rr.(*NIMLOC).NIMLOC = rd.(rdata.NIMLOC) },
	TypeOPENPGPKEY: func(rr RR, rd RDATA) { rr.(*OPENPGPKEY).OPENPGPKEY = rd.(rdata.OPENPGPKEY) },
	TypeCSYNC:      func(rr RR, rd RDATA) { rr.(*CSYNC).CSYNC = rd.(rdata.CSYNC) },
	TypeZONEMD:     func(rr RR, rd RDATA) { rr.(*ZONEMD).ZONEMD = rd.(rdata.ZONEMD) },
	TypeRESINFO:    func(rr RR, rd RDATA) { rr.(*RESINFO).TXT.TXT = rd.(rdata.TXT) },
	TypeSVCB:       func(rr RR, rd RDATA) { rr.(*SVCB).SVCB = rd.(rdata.SVCB) },
	TypeHTTPS:      func(rr RR, rd RDATA) { rr.(*HTTPS).SVCB.SVCB = rd.(rdata.SVCB) },
	TypeDELEG:      func(rr RR, rd RDATA) { rr.(*DELEG).DELEG = rd.(rdata.DELEG) },
	TypeDELEGI:     func(rr RR, rd RDATA) { rr.(*DELEGI).DELEG.DELEG = rd.(rdata.DELEG) },
	TypeDSYNC:      func(rr RR, rd RDATA) { rr.(*DSYNC).DSYNC = rd.(rdata.DSYNC) },
	TypeANY:        func(rr RR, rd RDATA) {},
	TypeAXFR:       func(rr RR, rd RDATA) {},
	TypeIXFR:       func(rr RR, rd RDATA) {},
	TypeTSIG:       func(rr RR, rd RDATA) { rr.(*TSIG).TSIG = rd.(rdata.TSIG) },
}

func parseData(r io.Reader, rrtype uint16, o string) (RDATA, error) {
	c := dnslex.New(r, StringToType, StringToCode, StringToClass)

	switch rrtype {
	case TypeNULL:
		rd := rdata.NULL{}
		pe := parseNULL(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNXNAME:
		rd := rdata.NXNAME{}
		pe := parseNXNAME(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeCNAME:
		rd := rdata.CNAME{}
		pe := parseCNAME(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeHINFO:
		rd := rdata.HINFO{}
		pe := parseHINFO(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeMB:
		rd := rdata.MB{}
		pe := parseMB(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeMG:
		rd := rdata.MG{}
		pe := parseMG(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeMINFO:
		rd := rdata.MINFO{}
		pe := parseMINFO(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeMR:
		rd := rdata.MR{}
		pe := parseMR(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeMF:
		rd := rdata.MF{}
		pe := parseMF(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeMD:
		rd := rdata.MD{}
		pe := parseMD(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeMX:
		rd := rdata.MX{}
		pe := parseMX(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeAFSDB:
		rd := rdata.AFSDB{}
		pe := parseAFSDB(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeX25:
		rd := rdata.X25{}
		pe := parseX25(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeISDN:
		rd := rdata.ISDN{}
		pe := parseISDN(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeRT:
		rd := rdata.RT{}
		pe := parseRT(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNS:
		rd := rdata.NS{}
		pe := parseNS(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypePTR:
		rd := rdata.PTR{}
		pe := parsePTR(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeRP:
		rd := rdata.RP{}
		pe := parseRP(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeSOA:
		rd := rdata.SOA{}
		pe := parseSOA(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeTXT:
		rd := rdata.TXT{}
		pe := parseTXT(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeSPF:
		rd := rdata.TXT{}
		pe := parseTXT(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeAVC:
		rd := rdata.TXT{}
		pe := parseTXT(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeWALLET:
		rd := rdata.TXT{}
		pe := parseTXT(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeCLA:
		rd := rdata.TXT{}
		pe := parseTXT(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeIPN:
		rd := rdata.IPN{}
		pe := parseIPN(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeSRV:
		rd := rdata.SRV{}
		pe := parseSRV(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNAPTR:
		rd := rdata.NAPTR{}
		pe := parseNAPTR(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeCERT:
		rd := rdata.CERT{}
		pe := parseCERT(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeDNAME:
		rd := rdata.DNAME{}
		pe := parseDNAME(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeA:
		rd := rdata.A{}
		pe := parseA(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeAAAA:
		rd := rdata.AAAA{}
		pe := parseAAAA(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypePX:
		rd := rdata.PX{}
		pe := parsePX(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeGPOS:
		rd := rdata.GPOS{}
		pe := parseGPOS(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeLOC:
		rd := rdata.LOC{}
		pe := parseLOC(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeSIG:
		rd := rdata.RRSIG{}
		pe := parseRRSIG(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeRRSIG:
		rd := rdata.RRSIG{}
		pe := parseRRSIG(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNXT:
		rd := rdata.NSEC{}
		pe := parseNSEC(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNSEC:
		rd := rdata.NSEC{}
		pe := parseNSEC(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeDLV:
		rd := rdata.DS{}
		pe := parseDS(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeCDS:
		rd := rdata.DS{}
		pe := parseDS(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeDS:
		rd := rdata.DS{}
		pe := parseDS(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeKX:
		rd := rdata.KX{}
		pe := parseKX(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeTA:
		rd := rdata.TA{}
		pe := parseTA(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeTALINK:
		rd := rdata.TALINK{}
		pe := parseTALINK(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeSSHFP:
		rd := rdata.SSHFP{}
		pe := parseSSHFP(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeKEY:
		rd := rdata.DNSKEY{}
		pe := parseDNSKEY(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeCDNSKEY:
		rd := rdata.DNSKEY{}
		pe := parseDNSKEY(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeDNSKEY:
		rd := rdata.DNSKEY{}
		pe := parseDNSKEY(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeRKEY:
		rd := rdata.RKEY{}
		pe := parseRKEY(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNSAPPTR:
		rd := rdata.NSAPPTR{}
		pe := parseNSAPPTR(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNSEC3:
		rd := rdata.NSEC3{}
		pe := parseNSEC3(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNSEC3PARAM:
		rd := rdata.NSEC3PARAM{}
		pe := parseNSEC3PARAM(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeTKEY:
		rd := rdata.TKEY{}
		pe := parseTKEY(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeRFC3597:
		rd := rdata.RFC3597{}
		pe := parseRFC3597(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeURI:
		rd := rdata.URI{}
		pe := parseURI(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeDHCID:
		rd := rdata.DHCID{}
		pe := parseDHCID(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeTLSA:
		rd := rdata.TLSA{}
		pe := parseTLSA(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeSMIMEA:
		rd := rdata.SMIMEA{}
		pe := parseSMIMEA(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeHIP:
		rd := rdata.HIP{}
		pe := parseHIP(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNINFO:
		rd := rdata.NINFO{}
		pe := parseNINFO(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNID:
		rd := rdata.NID{}
		pe := parseNID(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeL32:
		rd := rdata.L32{}
		pe := parseL32(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeL64:
		rd := rdata.L64{}
		pe := parseL64(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeLP:
		rd := rdata.LP{}
		pe := parseLP(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeEUI48:
		rd := rdata.EUI48{}
		pe := parseEUI48(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeEUI64:
		rd := rdata.EUI64{}
		pe := parseEUI64(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeCAA:
		rd := rdata.CAA{}
		pe := parseCAA(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeUID:
		rd := rdata.UID{}
		pe := parseUID(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeGID:
		rd := rdata.GID{}
		pe := parseGID(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeUINFO:
		rd := rdata.UINFO{}
		pe := parseUINFO(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeEID:
		rd := rdata.EID{}
		pe := parseEID(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeNIMLOC:
		rd := rdata.NIMLOC{}
		pe := parseNIMLOC(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeOPENPGPKEY:
		rd := rdata.OPENPGPKEY{}
		pe := parseOPENPGPKEY(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeCSYNC:
		rd := rdata.CSYNC{}
		pe := parseCSYNC(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeZONEMD:
		rd := rdata.ZONEMD{}
		pe := parseZONEMD(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeRESINFO:
		rd := rdata.TXT{}
		pe := parseTXT(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeSVCB:
		rd := rdata.SVCB{}
		pe := parseSVCB(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeHTTPS:
		rd := rdata.SVCB{}
		pe := parseSVCB(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeDELEG:
		rd := rdata.DELEG{}
		pe := parseDELEG(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeDELEGI:
		rd := rdata.DELEG{}
		pe := parseDELEG(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeDSYNC:
		rd := rdata.DSYNC{}
		pe := parseDSYNC(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeANY:
		rd := rdata.ANY{}
		pe := parseANY(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeAXFR:
		rd := rdata.AXFR{}
		pe := parseAXFR(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeIXFR:
		rd := rdata.IXFR{}
		pe := parseIXFR(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	case TypeTSIG:
		rd := rdata.TSIG{}
		pe := parseTSIG(&rd, c, o)
		if pe != nil {
			return rd, pe
		}
		return rd, pe

	}
}
