on:
  schedule:
  - cron: '32 23 * * *'

env:
  FUZZ: 3h

jobs:
  fuzz:
    runs-on: atoom
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ vars.GOVERSION }}
      - run: |
          go test -v -fuzz=FuzzMsgPack -run=XXXXX
          go test -v -fuzz=FuzzNew -run=XXXXX
