on:
  schedule:
    - cron: "32 11 * * 6"

env:
  FUZZ: 2h

jobs:
  fuzzNew:
    runs-on: atoom
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ vars.GOVERSION }}
      - run: |
          go test -v -fuzz=FuzzNew -run=XXXXX
