on: [push]

jobs:
  perf:
    runs-on: atoom
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ vars.GOVERSION }}
      - uses: https://github.com/thollander/actions-comment-pull-request@v3
        with:
          name: benchstat
          path: /tmp/benchstat
      - run: |
          wget https://miek.nl/libldns3_1.8.3-1+b1_amd64.deb && dpkg -i libldns3_1.8.3-1+b1_amd64.deb
          wget https://miek.nl/dnsperf_2.10.0-2_amd64.deb && dpkg -i dnsperf_2.10.0-2_amd64.deb
          cd cmd/reflect
          go build
          export HOSTNAME=runner
          make new.txt
          go install golang.org/x/perf/cmd/benchstat@latest
          make stat > /tmp/benchstat
