on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: atoom
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ vars.GOVERSION }}
      - run: |
          (cd cmd/atomdns; go build)
          apt-get update
          apt-get install -y dpkg-dev debhelper lsb-release build-essential
          (cd cmd/atomdns/_release; dpkg-buildpackage -us -uc)
  release:
    runs-on: atoom
    steps:
      - uses: actions/upload-artifact@v6
        with:
          name: atomdns-deb
          path: cmd/atomdns/*.deb
