// Code generated by "go run err_generate.go"; DO NOT EDIT.

package refuse

import (
	"fmt"
	"log/slog"
)

func (h *Refuse) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Refuse) Key() string { return "refuse" }

var log = func() *slog.Logger { return slog.Default().With("handler", "refuse") }
