// Code generated by "go run err_generate.go"; DO NOT EDIT.

package whoami

import (
	"fmt"
	"log/slog"
)

func (w *Whoami) Err(err error) error { return fmt.Errorf("%s: %s", w.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (w *Whoami) Key() string { return "whoami" }

var log = func() *slog.Logger { return slog.Default().With("handler", "whoami") }
