// Code generated by "go run err_generate.go"; DO NOT EDIT.

package whoami

import (
	"fmt"
	"log/slog"
)

func (h *Whoami) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Whoami) Key() string { return "whoami" }

var log = slog.Default().With("handler", "whoami")
