// Code generated by "go run err_generate.go"; DO NOT EDIT.

package nsid

import "fmt"
import "log/slog"

func (h *Nsid) Err(err error) error { return fmt.Errorf("handler.nsid: %s", err.Error()) }

var log = slog.Default().With("handler", "nsid")
