// Code generated by "go run err_generate.go"; DO NOT EDIT.

package nsid

import "fmt"
import "log/slog"

func (h *Nsid) Err(err error) error { return fmt.Errorf("%s: %s", Nsid.Key(), err.Error()) }

func (h *Nsid) Key() string { return "handler.nsid" }

var log = slog.Default().With("handler", "nsid")
