// Code generated by "go run err_generate.go"; DO NOT EDIT.

package nsid

import (
	"fmt"
	"log/slog"
)

func (h *Nsid) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Nsid) Key() string { return "nsid" }

var log = slog.Default().With("handler", "nsid")
