// Code generated by "go run err_generate.go"; DO NOT EDIT.

package cookie

import (
	"fmt"
	"log/slog"
)

func (c *Cookie) Err(err error) error { return fmt.Errorf("%s: %s", c.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (c *Cookie) Key() string { return "cookie" }

var log = func() *slog.Logger { return slog.Default().With("handler", "cookie") }
