// Code generated by "go run err_generate.go"; DO NOT EDIT.

package cookie

import (
	"fmt"
	"log/slog"
)

func (h *Cookie) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Cookie) Key() string { return "cookie" }

var log = slog.Default().With("handler", h.Key())
