// Code generated by "go run err_generate.go"; DO NOT EDIT.

package refuse

import "fmt"
import "log/slog"

func (h *Refuse) Err(err error) error { return fmt.Errorf("handler.refuse: %s", err.Error()) }

var log = slog.Default().With("handler", "refuse")
