// Code generated by "go run err_generate.go"; DO NOT EDIT.

package acl

import (
	"fmt"
	"log/slog"
)

func (a *Acl) Err(err error) error { return fmt.Errorf("%s: %s", a.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (a *Acl) Key() string { return "acl" }

var log = func() *slog.Logger { return slog.Default().With("handler", "acl") }
