// Code generated by "go run err_generate.go"; DO NOT EDIT.

package acl

import (
	"fmt"
	"log/slog"
)

func (h *Acl) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Acl) Key() string { return "acl" }

var log = slog.Default().With("handler", "acl")
