// Code generated by "go run err_generate.go"; DO NOT EDIT.

package metrics

import (
	"fmt"
	"log/slog"
)

func (h *Metrics) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Metrics) Key() string { return "metrics" }

var log = slog.Default().With("handler", h.Key())
