// Code generated by "go run err_generate.go"; DO NOT EDIT.

package as112

import (
	"fmt"
	"log/slog"
)

func (a *As112) Err(err error) error { return fmt.Errorf("%s: %s", a.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (a *As112) Key() string { return "as112" }

var log = func() *slog.Logger { return slog.Default().With("handler", "as112") }
