// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbfile

import "fmt"
import "log/slog"

func (h *Dbfile) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Dbfile) Key() string { return "dbfile" }

var log = slog.Default().With("handler", "dbfile")
