// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbfile

import "fmt"
import "log/slog"

func (h *Dbfile) Err(err error) error { return fmt.Errorf("handler.dbfile: %s", err.Error()) }

var log = slog.Default().With("handler", "dbfile")
