// Code generated by "go run err_generate.go"; DO NOT EDIT.

package nsid

import (
	"fmt"
	"log/slog"
)

func (n *Nsid) Err(err error) error { return fmt.Errorf("%s: %w", n.Key(), err) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (n *Nsid) Key() string { return "nsid" }

var log = func() *slog.Logger { return slog.Default().With("handler", "nsid") }
