// Code generated by "go run err_generate.go"; DO NOT EDIT.

package empty

import (
	"fmt"
	"log/slog"
)

func (e *Empty) Err(err error) error { return fmt.Errorf("%s: %w", e.Key(), err) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (e *Empty) Key() string { return "empty" }

var log = func() *slog.Logger { return slog.Default().With("handler", "empty") }
