// Code generated by "go run err_generate.go"; DO NOT EDIT.

package any

import (
	"fmt"
	"log/slog"
)

func (a *Any) Err(err error) error { return fmt.Errorf("%s: %s", a.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (a *Any) Key() string { return "any" }

var log = func() *slog.Logger { return slog.Default().With("handler", "any") }
