// Code generated by "go run err_generate.go"; DO NOT EDIT.

package any

import (
	"fmt"
	"log/slog"
)

func (h *Any) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Any) Key() string { return "any" }

var log = slog.Default().With("handler", "any")
