// Code generated by "go run err_generate.go"; DO NOT EDIT.

package store

import (
	"fmt"
	"log/slog"
)

func (h *Store) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Store) Key() string { return "store" }

var log = slog.Default().With("handler", "store")
