// Code generated by "go run err_generate.go"; DO NOT EDIT.

package chaos

import "fmt"
import "log/slog"

func (h *Chaos) Err(err error) error { return fmt.Errorf("%s: %s", Chaos.Key(), err.Error()) }

func (h *Chaos) Key() string { return "handler.chaos" }

var log = slog.Default().With("handler", "chaos")
