// Code generated by "go run err_generate.go"; DO NOT EDIT.

package chaos

import "fmt"
import "log/slog"

func (h *Chaos) Err(err error) error { return fmt.Errorf("handler.chaos: %s", err.Error()) }

var log = slog.Default().With("handler", "chaos")
