// Code generated by "go run err_generate.go"; DO NOT EDIT.

package unpack

import (
	"fmt"
	"log/slog"
)

func (u *Unpack) Err(err error) error { return fmt.Errorf("%s: %s", u.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (u *Unpack) Key() string { return "unpack" }

var log = func() *slog.Logger { return slog.Default().With("handler", "unpack") }
