// Code generated by "go run err_generate.go"; DO NOT EDIT.

package unpack

import (
	"fmt"
	"log/slog"
)

func (h *Unpack) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Unpack) Key() string { return "unpack" }

var log = slog.Default().With("handler", "unpack")
