// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbhost

import (
	"fmt"
	"log/slog"
)

func (d *Dbhost) Err(err error) error { return fmt.Errorf("%s: %s", d.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (d *Dbhost) Key() string { return "dbhost" }

var log = func() *slog.Logger { return slog.Default().With("handler", "dbhost") }
