// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbhost

import (
	"fmt"
	"log/slog"
)

func (h *Dbhost) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Dbhost) Key() string { return "dbhost" }

var log = slog.Default().With("handler", "dbhost")
