// Code generated by "go run err_generate.go"; DO NOT EDIT.

package drunk

import (
	"fmt"
	"log/slog"
)

func (d *Drunk) Err(err error) error { return fmt.Errorf("%s: %s", d.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (d *Drunk) Key() string { return "drunk" }

var log = func() *slog.Logger { return slog.Default().With("handler", "drunk") }
