// Code generated by "go run err_generate.go"; DO NOT EDIT.

package drunk

import (
	"fmt"
	"log/slog"
)

func (h *Drunk) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Drunk) Key() string { return "drunk" }

var log = slog.Default().With("handler", "drunk")
