// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbsqlite

import (
	"fmt"
	"log/slog"
)

func (d *Dbsqlite) Err(err error) error { return fmt.Errorf("%s: %s", d.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (d *Dbsqlite) Key() string { return "dbsqlite" }

var log = func() *slog.Logger { return slog.Default().With("handler", "dbsqlite") }
