// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbsqlite

import (
	"fmt"
	"log/slog"
)

func (h *Dbsqlite) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *Dbsqlite) Key() string { return "dbsqlite" }

var log = slog.Default().With("handler", "dbsqlite")
