// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbsqlite

import (
	"fmt"
	"log/slog"

	"codeberg.org/miekg/dns/cmd/atomdns/internal/dnslog"
)

func (d *Dbsqlite) Err(err error) error { return fmt.Errorf("%s: %w", d.Key(), err) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (d *Dbsqlite) Key() string { return "dbsqlite" }

var log = func() *slog.Logger { return slog.Default().With("handler", "dbsqlite") }
