// Code generated by "go run err_generate.go"; DO NOT EDIT.

package msgcache

import (
	"fmt"
	"log/slog"
)

func (m *Msgcache) Err(err error) error { return fmt.Errorf("%s: %s", m.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (m *Msgcache) Key() string { return "msgcache" }

var log = func() *slog.Logger { return slog.Default().With("handler", "msgcache") }
