// Code generated by "go run err_generate.go"; DO NOT EDIT.

package url

import (
	"fmt"
	"log/slog"
)

func (u *Url) Err(err error) error { return fmt.Errorf("%s: %w", u.Key(), err) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (u *Url) Key() string { return "url" }

var log = func() *slog.Logger { return slog.Default().With("handler", "url") }
