// Code generated by "go run err_generate.go"; DO NOT EDIT.

package global

import (
	"fmt"
	"log/slog"
)

func (h *Global) Err(err error) error { return fmt.Errorf("handler.global: %s", err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

var log = slog.Default().With("handler", "global")
