// Code generated by "go run err_generate.go"; DO NOT EDIT.

package global

import (
	"fmt"
	"log/slog"
)

func (g *Global) Err(err error) error { return fmt.Errorf("%s: %w", g.Key(), err) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (g *Global) Key() string { return "global" }

var log = func() *slog.Logger { return slog.Default().With("handler", "global") }
