// Code generated by "go run err_generate.go"; DO NOT EDIT.

package geoip

import (
	"fmt"
	"log/slog"
)

func (h *Geoip) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Geoip) Key() string { return "geoip" }

var log = slog.Default().With("handler", "geoip")
