// Code generated by "go run err_generate.go"; DO NOT EDIT.

package geoip

import (
	"fmt"
	"log/slog"
)

func (g *Geoip) Err(err error) error { return fmt.Errorf("%s: %s", g.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (g *Geoip) Key() string { return "geoip" }

var log = func() *slog.Logger { return slog.Default().With("handler", "geoip") }
