// Code generated by "go run err_generate.go"; DO NOT EDIT.

package whoami

import "fmt"
import "log/slog"

func (h *Whoami) Err(err error) error { return fmt.Errorf("handler.whoami: %s", err.Error()) }

var log = slog.Default().With("handler", "whoami")
