// Code generated by "go run err_generate.go"; DO NOT EDIT.

package kill

import (
	"fmt"
	"log/slog"

	"codeberg.org/miekg/dns/cmd/atomdns/internal/dnslog"
)

func (k *Kill) Err(err error) error { return fmt.Errorf("%s: %w", k.Key(), err) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (k *Kill) Key() string { return "kill" }

var log = func() *slog.Logger { return slog.Default().With("handler", "kill") }
