// Code generated by "go run err_generate.go"; DO NOT EDIT.

package kill

import (
	"fmt"
	"log/slog"
)

func (h *Kill) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Kill) Key() string { return "kill" }

var log = func() *slog.Logger { return slog.Default().With("handler", "kill") }
