// Code generated by "go run err_generate.go"; DO NOT EDIT.

package as112

import "fmt"
import "log/slog"

func (h *As112) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func (h *As112) Key() string { return "as112" }

var log = slog.Default().With("handler", "as112")
