// Code generated by "go run err_generate.go"; DO NOT EDIT.

package template

import (
	"fmt"
	"log/slog"
)

func (h *Template) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Template) Key() string { return "template" }

var log = slog.Default().With("handler", "template")
