// Code generated by "go run err_generate.go"; DO NOT EDIT.

package template

import (
	"fmt"
	"log/slog"
)

func (t *Template) Err(err error) error { return fmt.Errorf("%s: %w", t.Key(), err) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (t *Template) Key() string { return "template" }

var log = func() *slog.Logger { return slog.Default().With("handler", "template") }
