// Code generated by "go run err_generate.go"; DO NOT EDIT.

package subnet

import (
	"fmt"
	"log/slog"
)

func (h *Subnet) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Subnet) Key() string { return "subnet" }

var log = func() *slog.Logger { return slog.Default().With("handler", "subnet") }
