steps:
  build:
    when:
      event: [push, pull_request]
    image: golang:tip
    commands:
      - go get
      - go build
      - go test -race -v ./...
      - go generate ./...
      - (cd cmd/atomdns; GOOS=windows go build)
      - (cd cmd/atomdns; GOOS=darwin go build)
