// Code generated by "go run len_generate.go"; DO NOT EDIT.

package rdata

import (
	"encoding/base64"
	"net"
)

func (rdata NULL) Len() int {
	l := 0
	l += len(rdata.Null)
	return l
}

func (rdata CNAME) Len() int {
	l := 0
	l += len(rdata.Target) + 1
	return l
}

func (rdata HINFO) Len() int {
	l := 0
	l += len(rdata.Cpu) + 1
	l += len(rdata.Os) + 1
	return l
}

func (rdata MB) Len() int {
	l := 0
	l += len(rdata.Mb) + 1
	return l
}

func (rdata MG) Len() int {
	l := 0
	l += len(rdata.Mg) + 1
	return l
}

func (rdata MINFO) Len() int {
	l := 0
	l += len(rdata.Rmail) + 1
	l += len(rdata.Email) + 1
	return l
}

func (rdata MR) Len() int {
	l := 0
	l += len(rdata.Mr) + 1
	return l
}

func (rdata MF) Len() int {
	l := 0
	l += len(rdata.Mf) + 1
	return l
}

func (rdata MD) Len() int {
	l := 0
	l += len(rdata.Md) + 1
	return l
}

func (rdata MX) Len() int {
	l := 0
	l += 2 // Preference
	l += len(rdata.Mx) + 1
	return l
}

func (rdata AFSDB) Len() int {
	l := 0
	l += 2 // Subtype
	l += len(rdata.Hostname) + 1
	return l
}

func (rdata X25) Len() int {
	l := 0
	l += len(rdata.PSDNAddress) + 1
	return l
}

func (rdata ISDN) Len() int {
	l := 0
	l += len(rdata.Address) + 1
	l += len(rdata.SubAddress) + 1
	return l
}

func (rdata RT) Len() int {
	l := 0
	l += 2 // Preference
	l += len(rdata.Host) + 1
	return l
}

func (rdata NS) Len() int {
	l := 0
	l += len(rdata.Ns) + 1
	return l
}

func (rdata PTR) Len() int {
	l := 0
	l += len(rdata.Ptr) + 1
	return l
}

func (rdata RP) Len() int {
	l := 0
	l += len(rdata.Mbox) + 1
	l += len(rdata.Txt) + 1
	return l
}

func (rdata SOA) Len() int {
	l := 0
	l += len(rdata.Ns) + 1
	l += len(rdata.Mbox) + 1
	l += 4 // Serial
	l += 4 // Refresh
	l += 4 // Retry
	l += 4 // Expire
	l += 4 // Minttl
	return l
}

func (rdata TXT) Len() int {
	l := 0
	for _, x := range rdata.Txt {
		l += len(x) + 1
	}
	return l
}

func (rdata IPN) Len() int {
	l := 0
	l += 8 // Node
	return l
}

func (rdata SRV) Len() int {
	l := 0
	l += 2 // Priority
	l += 2 // Weight
	l += 2 // Port
	l += len(rdata.Target) + 1
	return l
}

func (rdata NAPTR) Len() int {
	l := 0
	l += 2 // Order
	l += 2 // Preference
	l += len(rdata.Flags) + 1
	l += len(rdata.Service) + 1
	l += len(rdata.Regexp) + 1
	l += len(rdata.Replacement) + 1
	return l
}

func (rdata CERT) Len() int {
	l := 0
	l += 2 // Type
	l += 2 // KeyTag
	l++    // Algorithm
	l += base64.StdEncoding.DecodedLen(len(rdata.Certificate))
	return l
}

func (rdata DNAME) Len() int {
	l := 0
	l += len(rdata.Target) + 1
	return l
}

func (rdata A) Len() int {
	l := 0
	if rdata.Addr.IsValid() {
		l += net.IPv4len
	}
	return l
}

func (rdata AAAA) Len() int {
	l := 0
	if rdata.Addr.IsValid() {
		l += net.IPv6len
	}
	return l
}

func (rdata PX) Len() int {
	l := 0
	l += 2 // Preference
	l += len(rdata.Map822) + 1
	l += len(rdata.Mapx400) + 1
	return l
}

func (rdata GPOS) Len() int {
	l := 0
	l += len(rdata.Longitude) + 1
	l += len(rdata.Latitude) + 1
	l += len(rdata.Altitude) + 1
	return l
}

func (rdata LOC) Len() int {
	l := 0
	l++    // Version
	l++    // Size
	l++    // HorizPre
	l++    // VertPre
	l += 4 // Latitude
	l += 4 // Longitude
	l += 4 // Altitude
	return l
}

func (rdata RRSIG) Len() int {
	l := 0
	l += 2 // TypeCovered
	l++    // Algorithm
	l++    // Labels
	l += 4 // OrigTTL
	l += 4 // Expiration
	l += 4 // Inception
	l += 2 // KeyTag
	l += len(rdata.SignerName) + 1
	l += base64.StdEncoding.DecodedLen(len(rdata.Signature))
	return l
}

func (rdata DS) Len() int {
	l := 0
	l += 2 // KeyTag
	l++    // Algorithm
	l++    // DigestType
	l += len(rdata.Digest) / 2
	return l
}

func (rdata KX) Len() int {
	l := 0
	l += 2 // Preference
	l += len(rdata.Exchanger) + 1
	return l
}

func (rdata TA) Len() int {
	l := 0
	l += 2 // KeyTag
	l++    // Algorithm
	l++    // DigestType
	l += len(rdata.Digest) / 2
	return l
}

func (rdata TALINK) Len() int {
	l := 0
	l += len(rdata.PreviousName) + 1
	l += len(rdata.NextName) + 1
	return l
}

func (rdata SSHFP) Len() int {
	l := 0
	l++ // Algorithm
	l++ // Type
	l += len(rdata.FingerPrint) / 2
	return l
}

func (rdata DNSKEY) Len() int {
	l := 0
	l += 2 // Flags
	l++    // Protocol
	l++    // Algorithm
	l += base64.StdEncoding.DecodedLen(len(rdata.PublicKey))
	return l
}

func (rdata RKEY) Len() int {
	l := 0
	l += 2 // Flags
	l++    // Protocol
	l++    // Algorithm
	l += base64.StdEncoding.DecodedLen(len(rdata.PublicKey))
	return l
}

func (rdata NSAPPTR) Len() int {
	l := 0
	l += len(rdata.Ptr) + 1
	return l
}

func (rdata NSEC3PARAM) Len() int {
	l := 0
	l++    // Hash
	l++    // Flags
	l += 2 // Iterations
	l++    // SaltLength
	l += len(rdata.Salt) / 2
	return l
}

func (rdata TKEY) Len() int {
	l := 0
	l += len(rdata.Algorithm) + 1
	l += 4 // Inception
	l += 4 // Expiration
	l += 2 // Mode
	l += 2 // Error
	l += 2 // KeySize
	l += len(rdata.Key) / 2
	l += 2 // OtherLen
	l += len(rdata.OtherData) / 2
	return l
}

func (rdata RFC3597) Len() int {
	l := 0
	l += len(rdata.Data) / 2
	return l
}

func (rdata URI) Len() int {
	l := 0
	l += 2 // Priority
	l += 2 // Weight
	l += len(rdata.Target)
	return l
}

func (rdata DHCID) Len() int {
	l := 0
	l += base64.StdEncoding.DecodedLen(len(rdata.Digest))
	return l
}

func (rdata TLSA) Len() int {
	l := 0
	l++ // Usage
	l++ // Selector
	l++ // MatchingType
	l += len(rdata.Certificate) / 2
	return l
}

func (rdata SMIMEA) Len() int {
	l := 0
	l++ // Usage
	l++ // Selector
	l++ // MatchingType
	l += len(rdata.Certificate) / 2
	return l
}

func (rdata HIP) Len() int {
	l := 0
	l++    // HitLength
	l++    // PublicKeyAlgorithm
	l += 2 // PublicKeyLength
	l += len(rdata.Hit) / 2
	l += base64.StdEncoding.DecodedLen(len(rdata.PublicKey))
	for _, x := range rdata.RendezvousServers {
		l += len(x) + 1
	}
	return l
}

func (rdata NINFO) Len() int {
	l := 0
	for _, x := range rdata.ZSData {
		l += len(x) + 1
	}
	return l
}

func (rdata NID) Len() int {
	l := 0
	l += 2 // Preference
	l += 8 // NodeID
	return l
}

func (rdata L32) Len() int {
	l := 0
	l += 2 // Preference
	if rdata.Locator32.IsValid() {
		l += net.IPv4len
	}
	return l
}

func (rdata L64) Len() int {
	l := 0
	l += 2 // Preference
	l += 8 // Locator64
	return l
}

func (rdata LP) Len() int {
	l := 0
	l += 2 // Preference
	l += len(rdata.Fqdn) + 1
	return l
}

func (rdata EUI48) Len() int {
	l := 0
	l += 6 // Address
	return l
}

func (rdata EUI64) Len() int {
	l := 0
	l += 8 // Address
	return l
}

func (rdata CAA) Len() int {
	l := 0
	l++ // Flag
	l += len(rdata.Tag) + 1
	l += len(rdata.Value)
	return l
}

func (rdata UID) Len() int {
	l := 0
	l += 4 // Uid
	return l
}

func (rdata GID) Len() int {
	l := 0
	l += 4 // Gid
	return l
}

func (rdata UINFO) Len() int {
	l := 0
	l += len(rdata.Uinfo) + 1
	return l
}

func (rdata EID) Len() int {
	l := 0
	l += len(rdata.Endpoint) / 2
	return l
}

func (rdata NIMLOC) Len() int {
	l := 0
	l += len(rdata.Locator) / 2
	return l
}

func (rdata OPENPGPKEY) Len() int {
	l := 0
	l += base64.StdEncoding.DecodedLen(len(rdata.PublicKey))
	return l
}

func (rdata ZONEMD) Len() int {
	l := 0
	l += 4 // Serial
	l++    // Scheme
	l++    // Hash
	l += len(rdata.Digest) / 2
	return l
}

func (rdata SVCB) Len() int {
	l := 0
	l += 2 // Priority
	l += len(rdata.Target) + 1
	for _, x := range rdata.Value {
		l += x.Len()
	}
	return l
}

func (rdata DELEG) Len() int {
	l := 0
	for _, x := range rdata.Value {
		l += x.Len()
	}
	return l
}

func (rdata DSYNC) Len() int {
	l := 0
	l += 2 // Type
	l++    // Scheme
	l += 2 // Port
	l += len(rdata.Target) + 1
	return l
}

func (rdata TSIG) Len() int {
	l := 0
	l += len(rdata.Algorithm) + 1
	l += 6 // TimeSigned
	l += 2 // Fudge
	l += 2 // MACSize
	l += len(rdata.MAC) / 2
	l += 2 // OrigID
	l += 2 // Error
	l += 2 // OtherLen
	l += len(rdata.OtherData) / 2
	return l
}
