// Code generated by "go run err_generate.go"; DO NOT EDIT.

package root

import (
	"fmt"
	"log/slog"
)

func (r *Root) Err(err error) error { return fmt.Errorf("%s: %s", r.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (r *Root) Key() string { return "root" }

var log = func() *slog.Logger { return slog.Default().With("handler", "root") }
