// Code generated by "go run err_generate.go"; DO NOT EDIT.

package chaos

import (
	"fmt"
	"log/slog"
)

func (h *Chaos) Err(err error) error { return fmt.Errorf("%s: %s", h.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (h *Chaos) Key() string { return "chaos" }

var log = slog.Default().With("handler", "chaos")
