// Code generated by "go run err_generate.go"; DO NOT EDIT.

package chaos

import (
	"fmt"
	"log/slog"
)

func (c *Chaos) Err(err error) error { return fmt.Errorf("%s: %s", c.Key(), err.Error()) }

func Err(err error) slog.Attr { return slog.Any("error", err) }

func (c *Chaos) Key() string { return "chaos" }

var log = func() *slog.Logger { return slog.Default().With("handler", "chaos") }
